import React, { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Platform, Pressable, ScrollView, Share as RNShare, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import * as Haptics from "expo-haptics";

import { SPACING, RADIUS, FONT, FONT_DISPLAY } from "@/src/theme";
import { useTheme } from "@/src/theme_context/ThemeContext";
import { api } from "@/src/api/client";
import { tripApi } from "@/src/api/trip";
import type { TripLiveMember, TripStage, TripState } from "@/src/api/trip";
import { useAuth } from "@/src/auth/AuthContext";
import RatingBadge from "@/src/components/RatingBadge";
import UserBadges from "@/src/components/UserBadges";
import PoolMapView from "@/src/components/PoolMapView";
import ReportBlockModal from "@/src/components/ReportBlockModal";

const WEB_BASE_URL = "https://uni-pool-ruddy.vercel.app";
const CANCEL_REASONS = ["Plans changed", "No longer travelling", "Timing changed", "Safety concern", "Other"];
type ConfirmedTraveler = { user_id: string; name: string; email: string };
type Pickup = { pickup_point_id: string; label: string; notes?: string | null; lat: number; lng: number };
type Pool = {
  pool_id: string; user_id: string; user_name: string; user_email: string; from_location: string; to_location: string; travel_datetime: string;
  gender_preference: string; companions: number; total_seats?: number; luggage?: string | null; notes?: string | null; status?: string; trip_status?: string;
  user_rating_avg?: number | null; user_rating_count?: number; user_badges?: any[]; user_college_id?: any; confirmed_travelers?: ConfirmedTraveler[];
  my_request_status?: "pending" | "waitlisted" | "accepted" | "declined" | null; trip_conversation_id?: string | null;
  meeting_point?: { label?: string; notes?: string; lat?: number; lng?: number } | null; fare?: { amount?: number; currency?: string } | null; member_statuses?: Record<string, string>;
};

function fmtWhen(iso: string) { return new Date(iso).toLocaleString(undefined, { weekday: "short", day: "numeric", month: "short", hour: "numeric", minute: "2-digit", timeZone: "Asia/Kolkata" }); }
function prettyStatus(value?: string | null) { return (value || "planning").replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()); }
function countdown(iso: string) { const mins = Math.round((new Date(iso).getTime() - Date.now()) / 60000); if (mins < -30) return "Departure time passed"; if (mins < 0) return "Departure time"; if (mins < 60) return `Leaves in ${mins} min`; const h = Math.floor(mins / 60), m = mins % 60; if (h < 24) return `Leaves in ${h}h${m ? ` ${m}m` : ""}`; const d = Math.floor(h / 24); return `Leaves in ${d} day${d === 1 ? "" : "s"}`; }
function legacyStage(value?: string | null): TripStage {
  if (value === "completed") return "completed";
  if (value === "cancelled") return "cancelled";
  if (value === "in_progress" || value === "travelling") return "travelling";
  if (value === "meeting") return "meeting";
  if (value === "confirmed") return "confirmed";
  return "planning";
}

export default function PoolDetailScreen() {
  const { poolId } = useLocalSearchParams<{ poolId: string }>();
  const router = useRouter(); const { user } = useAuth(); const { colors } = useTheme(); const styles = useMemo(() => makeStyles(colors), [colors]);
  const [pool, setPool] = useState<Pool | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string | null>(null); const [showReport, setShowReport] = useState(false);
  const [tripState, setTripState] = useState<TripState | null>(null); const [liveMembers, setLiveMembers] = useState<TripLiveMember[]>([]);
  const [editingMeeting, setEditingMeeting] = useState(false); const [meetingLabel, setMeetingLabel] = useState(""); const [meetingNotes, setMeetingNotes] = useState(""); const [selectedPickup, setSelectedPickup] = useState<Pickup | null>(null); const [pickups, setPickups] = useState<Pickup[]>([]);
  const [editingFare, setEditingFare] = useState(false); const [fareAmount, setFareAmount] = useState(""); const [cancelOpen, setCancelOpen] = useState(false); const [cancelReason, setCancelReason] = useState(CANCEL_REASONS[0]); const [cancelNote, setCancelNote] = useState("");

  const load = useCallback(async () => {
    try {
      const [poolResult, pickupResult] = await Promise.allSettled([api.getPool(poolId as string), api.pickupPoints()]);
      if (poolResult.status !== "fulfilled" || !poolResult.value) throw new Error("This journey no longer exists.");
      const data = poolResult.value; setPool(data); setMeetingLabel(data.meeting_point?.label || ""); setMeetingNotes(data.meeting_point?.notes || "");
      if (pickupResult.status === "fulfilled") setPickups(pickupResult.value || []);
      const travellers = data.confirmed_travelers || [];
      const isParticipant = data.user_id === user?.user_id || travellers.some((t: ConfirmedTraveler) => t.user_id === user?.user_id);
      if (isParticipant) {
        const [stateResult, liveResult] = await Promise.allSettled([tripApi.state(data.pool_id), tripApi.live(data.pool_id)]);
        if (stateResult.status === "fulfilled") {
          setTripState(stateResult.value);
          const fareRupees = Number(stateResult.value.final_fare_paise || 0) / 100;
          setFareAmount(fareRupees > 0 ? String(fareRupees) : data.fare?.amount ? String(data.fare.amount) : "");
        } else setFareAmount(data.fare?.amount ? String(data.fare.amount) : "");
        if (liveResult.status === "fulfilled") setLiveMembers(liveResult.value || []);
      } else setFareAmount(data.fare?.amount ? String(data.fare.amount) : "");
    } catch { Alert.alert("Not found", "This journey no longer exists."); router.back(); } finally { setLoading(false); }
  }, [poolId, user?.user_id]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  if (loading || !pool) return <SafeAreaView style={styles.safe}><View style={styles.loading}><ActivityIndicator color={colors.indigo} /></View></SafeAreaView>;

  const mine = pool.user_id === user?.user_id; const travelers = pool.confirmed_travelers || []; const participant = mine || travelers.some((t) => t.user_id === user?.user_id);
  const totalSeats = pool.total_seats || 4; const occupied = 1 + (pool.companions || 0) + travelers.length; const available = Math.max(0, totalSeats - occupied);
  const globalStage = tripState?.stage || legacyStage(pool.trip_status); const totalFare = tripState?.final_fare_paise ? Number(tripState.final_fare_paise) / 100 : Number(pool.fare?.amount || 0); const perPerson = totalFare > 0 ? totalFare / Math.max(1, occupied) : null;
  const liveByUser = new Map(liveMembers.map((member) => [member.user_id, member])); const myStatus = user?.user_id ? liveByUser.get(user.user_id)?.status || pool.member_statuses?.[user.user_id] : null; const noShowUnlocked = Date.now() >= new Date(pool.travel_datetime).getTime() + 30 * 60000;

  const share = async () => {
    const url = `${WEB_BASE_URL}/pool/${pool.pool_id}`; const people = [pool.user_name, ...travelers.map((t) => t.name)].join(", ");
    const text = participant ? `UniPool trip\n${pool.from_location} → ${pool.to_location}\n${fmtWhen(pool.travel_datetime)}\nTravellers: ${people}${pool.meeting_point?.label ? `\nMeeting: ${pool.meeting_point.label}` : ""}${pool.meeting_point?.notes ? ` · ${pool.meeting_point.notes}` : ""}\n${url}` : `Join this UniPool ride: ${pool.from_location} → ${pool.to_location} — ${url}`;
    if (Platform.OS === "web" && typeof navigator !== "undefined" && (navigator as any).share) { try { await (navigator as any).share({ title: "UniPool journey", text, url }); return; } catch {} }
    if (Platform.OS === "web" && typeof navigator !== "undefined" && navigator.clipboard) { try { await navigator.clipboard.writeText(text); Alert.alert("Trip summary copied", "Share it with someone you trust."); return; } catch {} }
    try { await RNShare.share({ message: text }); } catch {}
  };

  const request = async () => { const previous = pool.my_request_status; const optimistic = available > 0 ? "pending" : "waitlisted"; setPool({ ...pool, my_request_status: optimistic }); setBusy("request"); try { const result = await api.requestToJoin(pool.pool_id); setPool((current) => current ? { ...current, my_request_status: result.status } : current); Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); } catch (e: any) { setPool((current) => current ? { ...current, my_request_status: previous } : current); Alert.alert("Couldn't send request", e.message || "Try again"); } finally { setBusy(null); } };
  const setMemberStatus = async (status: string) => { if (!user?.user_id) return; const previous = [...liveMembers]; const optimistic: TripLiveMember = { ...(liveByUser.get(user.user_id) || { pool_id: pool.pool_id, user_id: user.user_id }), status }; setLiveMembers((rows) => [...rows.filter((row) => row.user_id !== user.user_id), optimistic]); setBusy(status); try { const updated = await tripApi.updateLive(pool.pool_id, { status }); setLiveMembers((rows) => [...rows.filter((row) => row.user_id !== user.user_id), updated]); Haptics.selectionAsync(); } catch (e: any) { setLiveMembers(previous); Alert.alert("Couldn't update status", e.message || "Try again"); } finally { setBusy(null); } };
  const setGlobalStatus = async (stage: TripStage) => { const previous = tripState; setTripState((current) => ({ ...(current || { pool_id: pool.pool_id }), stage } as TripState)); setBusy(stage); try { const updated = await tripApi.updateState(pool.pool_id, stage); setTripState(updated); const legacy = stage === "travelling" ? "in_progress" : stage; api.setJourneyStatus(pool.pool_id, legacy).catch(() => {}); Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); } catch (e: any) { setTripState(previous); Alert.alert("Couldn't update trip", e.message || "Try again"); } finally { setBusy(null); } };
  const choosePickup = (point: Pickup) => { setSelectedPickup(point); setMeetingLabel(point.label); setMeetingNotes(point.notes || ""); };
  const saveMeeting = async () => { if (!meetingLabel.trim()) return; setBusy("meeting-point"); try { const updated = await api.setMeetingPoint(pool.pool_id, { label: meetingLabel.trim(), notes: meetingNotes.trim() || null, lat: selectedPickup?.lat, lng: selectedPickup?.lng }); setPool((current) => current ? { ...current, ...updated } : current); setEditingMeeting(false); } catch (e: any) { Alert.alert("Couldn't set meeting point", e.message); } finally { setBusy(null); } };
  const saveFare = async () => { const amount = Number(fareAmount); if (!Number.isFinite(amount) || amount <= 0) return Alert.alert("Check fare", "Enter a valid fare above ₹0."); setBusy("fare"); try { const updated = await tripApi.setFare(pool.pool_id, Math.round(amount * 100)); setTripState(updated); setPool((current) => current ? { ...current, fare: { amount, currency: "INR" } } : current); api.setJourneyFare(pool.pool_id, amount).catch(() => {}); setEditingFare(false); } catch (e: any) { Alert.alert("Couldn't update fare", e.message || "Try again"); } finally { setBusy(null); } };
  const cancelJourney = async () => { setBusy("cancel"); try { await api.cancelJourney(pool.pool_id, cancelReason, cancelNote.trim() || undefined); try { setTripState(await tripApi.updateState(pool.pool_id, "cancelled")); } catch {} setPool((current) => current ? { ...current, trip_status: "cancelled", status: "closed" } : current); setCancelOpen(false); Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning); } catch (e: any) { Alert.alert("Couldn't cancel journey", e.message || "Try again"); } finally { setBusy(null); } };
  const reportNoShow = (id: string, name: string) => Alert.alert(`Report ${name.split(" ")[0]} as a no-show?`, "Use this only if they did not arrive for this confirmed trip.", [{ text: "Back", style: "cancel" }, { text: "Report no-show", style: "destructive", onPress: async () => { try { await api.reportNoShow(pool.pool_id, id); Alert.alert("Report received", "UniPool will keep this with the trip's safety record."); } catch (e: any) { Alert.alert("Couldn't report no-show", e.message || "Try again"); } } }]);
  const openTripChat = async () => { setBusy("chat"); try { const conv = pool.trip_conversation_id ? { conversation_id: pool.trip_conversation_id } : await api.ensureTripChat(pool.pool_id); if (conv?.conversation_id) router.push(`/chat/group/${conv.conversation_id}` as any); } catch (e: any) { Alert.alert("Couldn't open trip chat", e.message); } finally { setBusy(null); } };
  const repeat = () => router.push({ pathname: "/post-request", params: { from: pool.from_location, to: pool.to_location } } as any);

  return <SafeAreaView style={styles.safe} edges={["top"]}>
    <View style={styles.header}><Pressable onPress={() => router.back()} hitSlop={10} accessibilityLabel="Go back"><Ionicons name="arrow-back" size={24} color={colors.onSurface} /></Pressable><Text style={styles.headerTitle}>{participant ? "Trip Command Centre" : "Ride details"}</Text><View style={styles.headerActions}><Pressable onPress={share} hitSlop={10} accessibilityLabel="Share trip"><Ionicons name="share-outline" size={21} color={colors.onSurface} /></Pressable>{mine ? <Pressable onPress={() => router.push({ pathname: "/post-request", params: { edit: pool.pool_id } } as any)} accessibilityLabel="Edit journey"><Ionicons name="create-outline" size={21} color={colors.onSurface} /></Pressable> : <Pressable onPress={() => setShowReport(true)} accessibilityLabel="Safety and report options"><Ionicons name="ellipsis-vertical" size={21} color={colors.onSurface} /></Pressable>}</View></View>
    <ScrollView contentContainerStyle={styles.content}>
      <View style={styles.countdown}><View><Text style={styles.countdownLabel}>NEXT STEP</Text><Text style={styles.countdownValue}>{countdown(pool.travel_datetime)}</Text></View><Text style={styles.countdownWhen}>{fmtWhen(pool.travel_datetime)}</Text></View>
      <View style={styles.ownerRow}><View style={styles.avatar}><Text style={styles.avatarText}>{pool.user_name?.[0]?.toUpperCase() || "U"}</Text></View><View style={{ flex: 1 }}><Text style={styles.ownerName}>{pool.user_name}{mine ? " · you" : ""}</Text><RatingBadge avg={pool.user_rating_avg} count={pool.user_rating_count} /><UserBadges badges={pool.user_badges} /></View><View style={styles.statusPill}><Text style={styles.statusText}>{prettyStatus(globalStage)}</Text></View></View>
      <View style={styles.mapWrap}><PoolMapView pools={[pool]} /></View>
      <View style={styles.routeCard}><Row icon="location" color={colors.saffron} label="Pickup" value={pool.from_location} styles={styles} /><Row icon="flag" color={colors.indigo} label="Drop" value={pool.to_location} styles={styles} /><Row icon="time" color={colors.muted} label="Departure" value={fmtWhen(pool.travel_datetime)} styles={styles} /><Row icon="people" color={available ? colors.success : colors.error} label="Seats" value={`${occupied}/${totalSeats} filled · ${available ? `${available} available` : "full"}`} styles={styles} />{pool.luggage ? <Row icon="briefcase" color={colors.muted} label="Luggage" value={pool.luggage} styles={styles} /> : null}</View>

      {participant && <>
        <Text style={styles.sectionTitle}>Live trip status</Text><View style={styles.statusGrid}>{[["getting_ready", "Getting ready", "sparkles-outline"], ["on_the_way", "On my way", "car-outline"], ["at_pickup", "At pickup", "location-outline"], ["running_late", "Running late", "time-outline"]].map(([value, label, icon]) => <Pressable key={value} disabled={!!busy} onPress={() => setMemberStatus(value)} style={[styles.statusAction, myStatus === value && styles.statusActionActive]}><Ionicons name={icon as any} size={17} color={myStatus === value ? "#fff" : colors.indigo} /><Text style={[styles.statusActionText, myStatus === value && { color: "#fff" }]}>{label}</Text></Pressable>)}</View>
        <View style={styles.commandGrid}>
          <View style={styles.commandCard}><View style={styles.commandTop}><Ionicons name="location" size={19} color={colors.saffron} /><Text style={styles.cardTitle}>Meeting point</Text>{mine && <Pressable onPress={() => setEditingMeeting((v) => !v)}><Ionicons name="create-outline" size={18} color={colors.indigo} /></Pressable>}</View>{editingMeeting ? <>{pickups.length ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 6 }}>{pickups.map((point) => <Pressable key={point.pickup_point_id} onPress={() => choosePickup(point)} style={[styles.pickupChip, selectedPickup?.pickup_point_id === point.pickup_point_id && styles.pickupChipActive]}><Ionicons name="bookmark-outline" size={12} color={selectedPickup?.pickup_point_id === point.pickup_point_id ? "#fff" : colors.indigo} /><Text style={[styles.pickupText, selectedPickup?.pickup_point_id === point.pickup_point_id && { color: "#fff" }]}>{point.label}</Text></Pressable>)}</ScrollView> : null}<TextInput value={meetingLabel} onChangeText={(value) => { setMeetingLabel(value); setSelectedPickup(null); }} placeholder="e.g. Main Gate" placeholderTextColor={colors.muted} style={styles.input} /><TextInput value={meetingNotes} onChangeText={setMeetingNotes} placeholder="Optional pickup note" placeholderTextColor={colors.muted} style={styles.input} /><Pressable onPress={saveMeeting} style={styles.smallBtn}><Text style={styles.smallBtnText}>{busy === "meeting-point" ? "Saving…" : "Save meeting point"}</Text></Pressable></> : <><Text style={styles.commandValue}>{pool.meeting_point?.label || "Not set yet"}</Text>{pool.meeting_point?.notes ? <Text style={styles.commandSub}>{pool.meeting_point.notes}</Text> : <Text style={styles.commandSub}>Keep everyone aligned on the exact pickup.</Text>}</>}</View>
          <View style={styles.commandCard}><View style={styles.commandTop}><Ionicons name="cash" size={19} color={colors.success} /><Text style={styles.cardTitle}>Fare split</Text>{mine && <Pressable onPress={() => setEditingFare((v) => !v)}><Ionicons name="create-outline" size={18} color={colors.indigo} /></Pressable>}</View>{editingFare ? <><TextInput value={fareAmount} onChangeText={setFareAmount} keyboardType="numeric" placeholder="Estimated total fare" placeholderTextColor={colors.muted} style={styles.input} /><Pressable onPress={saveFare} style={styles.smallBtn}><Text style={styles.smallBtnText}>{busy === "fare" ? "Saving…" : "Update fare"}</Text></Pressable></> : <><Text style={styles.commandValue}>{totalFare > 0 ? `₹${totalFare.toFixed(0)} total` : "No fare added"}</Text><Text style={styles.commandSub}>{perPerson ? `≈ ₹${perPerson.toFixed(0)} per person with ${occupied} travelling` : "Add an estimate so everyone knows the likely split."}</Text></>}</View>
        </View>
        <View style={styles.primaryActions}><Pressable onPress={openTripChat} style={styles.chatBtn}>{busy === "chat" ? <ActivityIndicator color="#fff" /> : <><Ionicons name="chatbubbles" size={18} color="#fff" /><Text style={styles.chatBtnText}>Trip chat</Text></>}</Pressable><Pressable onPress={share} style={styles.secondaryBtn}><Ionicons name="shield-checkmark-outline" size={18} color={colors.indigo} /><Text style={styles.secondaryBtnText}>Share safety card</Text></Pressable></View>
        {mine && <>{<View style={styles.ownerControls}>{globalStage !== "meeting" && globalStage !== "travelling" && globalStage !== "completed" && globalStage !== "cancelled" ? <Pressable disabled={!!busy} onPress={() => setGlobalStatus("meeting")} style={styles.secondaryOwnerBtn}><Ionicons name="location-outline" size={15} color={colors.indigo} /><Text style={styles.secondaryOwnerText}>Meet-up</Text></Pressable> : null}{globalStage !== "travelling" && globalStage !== "completed" && globalStage !== "cancelled" ? <Pressable disabled={!!busy} onPress={() => setGlobalStatus("travelling")} style={styles.ownerBtn}><Ionicons name="play" size={15} color="#fff" /><Text style={styles.ownerBtnText}>Start trip</Text></Pressable> : null}{globalStage === "travelling" ? <Pressable disabled={!!busy} onPress={() => setGlobalStatus("completed")} style={[styles.ownerBtn, { backgroundColor: colors.success }]}><Ionicons name="checkmark" size={16} color="#fff" /><Text style={styles.ownerBtnText}>Complete trip</Text></Pressable> : null}{globalStage !== "completed" && globalStage !== "cancelled" ? <Pressable onPress={() => setCancelOpen((v) => !v)} style={styles.dangerBtn}><Text style={styles.dangerText}>Cancel journey</Text></Pressable> : null}</View>}{cancelOpen ? <View style={styles.cancelCard}><Text style={styles.cardTitle}>Why are you cancelling?</Text><View style={styles.reasonRow}>{CANCEL_REASONS.map((reason) => <Pressable key={reason} onPress={() => setCancelReason(reason)} style={[styles.reasonChip, cancelReason === reason && styles.reasonChipActive]}><Text style={[styles.reasonText, cancelReason === reason && { color: "#fff" }]}>{reason}</Text></Pressable>)}</View><TextInput value={cancelNote} onChangeText={setCancelNote} placeholder="Optional note for the trip record" placeholderTextColor={colors.muted} style={styles.input} /><Pressable disabled={busy === "cancel"} onPress={cancelJourney} style={styles.cancelConfirm}>{busy === "cancel" ? <ActivityIndicator color="#fff" /> : <Text style={styles.cancelConfirmText}>Confirm cancellation</Text>}</Pressable></View> : null}</>}
      </>}

      <Text style={styles.sectionTitle}>Travellers</Text><View style={styles.travellersCard}><Traveller name={pool.user_name} label="Trip owner" status={liveByUser.get(pool.user_id)?.status || pool.member_statuses?.[pool.user_id]} colors={colors} styles={styles} canNoShow={participant && !mine && noShowUnlocked} onNoShow={() => reportNoShow(pool.user_id, pool.user_name)} />{travelers.map((t) => <Traveller key={t.user_id} name={t.name} label="Confirmed" status={liveByUser.get(t.user_id)?.status || pool.member_statuses?.[t.user_id]} colors={colors} styles={styles} canNoShow={participant && t.user_id !== user?.user_id && noShowUnlocked} onNoShow={() => reportNoShow(t.user_id, t.name)} />)}{travelers.length === 0 ? <Text style={styles.commandSub}>No confirmed co-travellers yet.</Text> : null}</View>
      {pool.notes ? <View style={styles.notesCard}><Text style={styles.sectionLabel}>NOTES</Text><Text style={styles.notesText}>“{pool.notes}”</Text></View> : null}
      <Pressable onPress={repeat} style={styles.repeatCard}><Ionicons name="repeat" size={20} color={colors.indigo} /><View style={{ flex: 1 }}><Text style={styles.cardTitle}>Repeat this route</Text><Text style={styles.commandSub}>Prefill a new journey with the same pickup and destination.</Text></View><Ionicons name="arrow-forward" size={18} color={colors.saffron} /></Pressable>
    </ScrollView>

    {!mine && !participant && <View style={styles.footer}><Pressable onPress={() => router.push({ pathname: "/chat/[userId]", params: { userId: pool.user_id, name: pool.user_name } })} style={styles.messageBtn}><Ionicons name="chatbubble-outline" size={18} color={colors.indigo} /></Pressable>{pool.my_request_status === "accepted" ? <View style={[styles.requestBtn, { backgroundColor: colors.success }]}><Text style={styles.requestBtnText}>Confirmed</Text></View> : pool.my_request_status === "pending" ? <View style={[styles.requestBtn, styles.pendingBtn]}><Text style={styles.pendingText}>{busy === "request" ? "Sending…" : "Request pending"}</Text></View> : pool.my_request_status === "waitlisted" ? <View style={[styles.requestBtn, styles.pendingBtn]}><Text style={styles.pendingText}>{busy === "request" ? "Joining…" : "Waitlisted"}</Text></View> : <Pressable disabled={busy === "request"} onPress={request} style={styles.requestBtn}>{busy === "request" ? <ActivityIndicator color="#fff" /> : <Text style={styles.requestBtnText}>{available > 0 ? "Request to join" : "Join waitlist"}</Text>}</Pressable>}</View>}
    <ReportBlockModal visible={showReport} onClose={() => setShowReport(false)} userId={pool.user_id} userName={pool.user_name} poolId={pool.pool_id} onBlocked={() => router.back()} />
  </SafeAreaView>;
}

function Row({ icon, color, label, value, styles }: any) { return <View style={styles.row}><Ionicons name={icon} size={18} color={color} /><View style={{ flex: 1 }}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View></View>; }
function Traveller({ name, label, status, colors, styles, canNoShow, onNoShow }: any) { return <View style={styles.travellerRow}><View style={styles.smallAvatar}><Text style={styles.smallAvatarText}>{name?.[0]?.toUpperCase() || "U"}</Text></View><View style={{ flex: 1 }}><Text style={styles.travellerName}>{name}</Text><Text style={styles.commandSub}>{label}</Text></View>{status ? <View style={styles.memberPill}><View style={{ width: 5, height: 5, borderRadius: 3, backgroundColor: colors.success }} /><Text style={styles.memberText}>{prettyStatus(status)}</Text></View> : null}{canNoShow ? <Pressable onPress={onNoShow} hitSlop={8}><Ionicons name="alert-circle-outline" size={18} color={colors.error} /></Pressable> : null}</View>; }

const makeStyles = (colors: any) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.surface }, loading: { flex: 1, alignItems: "center", justifyContent: "center" }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: SPACING.lg, paddingVertical: SPACING.md, borderBottomWidth: 1, borderBottomColor: colors.border, backgroundColor: colors.card }, headerTitle: { color: colors.onSurface, fontWeight: "900", fontSize: FONT.lg, fontFamily: FONT_DISPLAY }, headerActions: { flexDirection: "row", gap: 14, alignItems: "center" },
  content: { width: "100%", maxWidth: 860, alignSelf: "center", padding: SPACING.lg, paddingBottom: 150 }, countdown: { minHeight: 74, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, backgroundColor: colors.surface2, borderWidth: 1, borderColor: colors.border, borderRadius: RADIUS.lg, padding: 14, marginBottom: 14 }, countdownLabel: { color: colors.saffron, fontSize: 9, fontWeight: "900", letterSpacing: 1 }, countdownValue: { color: colors.onSurface, fontFamily: FONT_DISPLAY, fontSize: 21, fontWeight: "900", marginTop: 2 }, countdownWhen: { color: colors.muted, fontSize: 10, fontWeight: "700", textAlign: "right" }, ownerRow: { flexDirection: "row", alignItems: "center", gap: 11, marginBottom: 15 }, avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.cream, alignItems: "center", justifyContent: "center" }, avatarText: { color: colors.indigo, fontSize: 18, fontWeight: "900" }, ownerName: { color: colors.onSurface, fontSize: 16, fontWeight: "900" }, statusPill: { backgroundColor: colors.surface2, borderRadius: 14, paddingHorizontal: 9, paddingVertical: 5 }, statusText: { color: colors.success, fontSize: 9, fontWeight: "900" },
  mapWrap: { height: 250, borderRadius: RADIUS.lg, overflow: "hidden", borderWidth: 1, borderColor: colors.border, marginBottom: 14 }, routeCard: { backgroundColor: colors.card, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: colors.border, padding: 14, gap: 12, marginBottom: 20 }, row: { flexDirection: "row", gap: 11, alignItems: "flex-start" }, rowLabel: { color: colors.muted, fontSize: 9, fontWeight: "900", textTransform: "uppercase", letterSpacing: .6 }, rowValue: { color: colors.onSurface, fontSize: 12, fontWeight: "700", marginTop: 2 }, sectionTitle: { color: colors.onSurface, fontSize: 15, fontWeight: "900", marginBottom: 9, marginTop: 4 },
  statusGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 18 }, statusAction: { flexGrow: 1, flexBasis: 150, minHeight: 44, borderRadius: 22, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, flexDirection: "row", gap: 7, alignItems: "center", justifyContent: "center", paddingHorizontal: 10 }, statusActionActive: { backgroundColor: colors.indigo, borderColor: colors.indigo }, statusActionText: { color: colors.onSurface, fontSize: 10, fontWeight: "800" }, commandGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 15 }, commandCard: { flexGrow: 1, flexBasis: 300, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: RADIUS.lg, padding: 14, gap: 8 }, commandTop: { flexDirection: "row", alignItems: "center", gap: 7 }, cardTitle: { color: colors.onSurface, fontSize: 12, fontWeight: "900", flex: 1 }, commandValue: { color: colors.onSurface, fontSize: 16, fontWeight: "900" }, commandSub: { color: colors.muted, fontSize: 10, lineHeight: 15 }, input: { backgroundColor: colors.surface2, borderRadius: 10, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 10, paddingVertical: 9, color: colors.onSurface, fontSize: 11 }, smallBtn: { backgroundColor: colors.indigo, borderRadius: 18, minHeight: 36, alignItems: "center", justifyContent: "center" }, smallBtnText: { color: "#fff", fontSize: 10, fontWeight: "900" }, pickupChip: { minHeight: 30, borderRadius: 15, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface2, paddingHorizontal: 9, flexDirection: "row", alignItems: "center", gap: 4 }, pickupChipActive: { backgroundColor: colors.indigo, borderColor: colors.indigo }, pickupText: { color: colors.onSurface, fontSize: 9, fontWeight: "800" },
  primaryActions: { flexDirection: "row", gap: 9, marginBottom: 14 }, chatBtn: { flex: 1, minHeight: 48, borderRadius: 24, backgroundColor: colors.indigo, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 7 }, chatBtnText: { color: "#fff", fontWeight: "900", fontSize: 11 }, secondaryBtn: { flex: 1, minHeight: 48, borderRadius: 24, borderWidth: 1, borderColor: colors.indigo, backgroundColor: colors.card, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 }, secondaryBtnText: { color: colors.indigo, fontWeight: "900", fontSize: 11 }, ownerControls: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 10 }, ownerBtn: { backgroundColor: colors.indigo, minHeight: 40, borderRadius: 20, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 }, ownerBtnText: { color: "#fff", fontWeight: "900", fontSize: 10 }, secondaryOwnerBtn: { minHeight: 40, borderRadius: 20, paddingHorizontal: 14, borderWidth: 1, borderColor: colors.indigo, backgroundColor: colors.card, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 }, secondaryOwnerText: { color: colors.indigo, fontWeight: "900", fontSize: 10 }, dangerBtn: { minHeight: 40, borderRadius: 20, paddingHorizontal: 14, borderWidth: 1, borderColor: colors.error, alignItems: "center", justifyContent: "center" }, dangerText: { color: colors.error, fontWeight: "900", fontSize: 10 }, cancelCard: { backgroundColor: colors.surface2, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: colors.error, padding: 12, gap: 9, marginBottom: 18 }, reasonRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, reasonChip: { minHeight: 32, borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card, paddingHorizontal: 9, alignItems: "center", justifyContent: "center" }, reasonChipActive: { backgroundColor: colors.error, borderColor: colors.error }, reasonText: { color: colors.onSurface, fontSize: 9, fontWeight: "800" }, cancelConfirm: { minHeight: 40, borderRadius: 20, backgroundColor: colors.error, alignItems: "center", justifyContent: "center" }, cancelConfirmText: { color: "#fff", fontSize: 10, fontWeight: "900" },
  travellersCard: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: RADIUS.lg, padding: 12, marginBottom: 16, gap: 9 }, travellerRow: { flexDirection: "row", alignItems: "center", gap: 9 }, smallAvatar: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.surface2, alignItems: "center", justifyContent: "center" }, smallAvatarText: { color: colors.indigo, fontWeight: "900", fontSize: 12 }, travellerName: { color: colors.onSurface, fontSize: 11, fontWeight: "800" }, memberPill: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: colors.surface2, borderRadius: 11, paddingHorizontal: 7, paddingVertical: 4 }, memberText: { color: colors.success, fontSize: 8, fontWeight: "900" }, notesCard: { backgroundColor: colors.card, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: colors.border, padding: 14, marginBottom: 12 }, sectionLabel: { color: colors.muted, fontSize: 9, fontWeight: "900", letterSpacing: .8 }, notesText: { color: colors.onSurface, fontSize: 11, fontStyle: "italic", marginTop: 7 }, repeatCard: { flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: RADIUS.lg, padding: 14 },
  footer: { flexDirection: "row", gap: 9, padding: SPACING.lg, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.surface }, messageBtn: { width: 48, height: 48, borderRadius: 24, borderWidth: 1, borderColor: colors.indigo, backgroundColor: colors.card, alignItems: "center", justifyContent: "center" }, requestBtn: { flex: 1, minHeight: 48, borderRadius: 24, backgroundColor: colors.indigo, alignItems: "center", justifyContent: "center" }, requestBtnText: { color: "#fff", fontSize: 11, fontWeight: "900" }, pendingBtn: { backgroundColor: colors.surface2, borderWidth: 1, borderColor: colors.border }, pendingText: { color: colors.indigo, fontSize: 11, fontWeight: "900" },
});
