import React from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import PersonalBudgetPanel from "@/src/components/PersonalBudgetPanel";
import { useTheme } from "@/src/theme_context/ThemeContext";
import { FONT_DISPLAY, SPACING } from "@/src/theme";
export default function BudgetScreen(){const router=useRouter(),{colors}=useTheme();return <SafeAreaView style={[styles.safe,{backgroundColor:colors.surface}]} edges={["top"]}><ScrollView contentContainerStyle={styles.page}><View style={styles.head}><Pressable onPress={()=>router.back()} style={[styles.back,{backgroundColor:colors.surface2,borderColor:colors.border}]}><Ionicons name="chevron-back" size={20} color={colors.onSurface}/></Pressable><View><Text style={[styles.eyebrow,{color:colors.saffron}]}>PERSONAL MONEY</Text><Text style={[styles.title,{color:colors.onSurface}]}>Budget without mixing debts</Text><Text style={[styles.sub,{color:colors.muted}]}>Set lightweight category limits and see a conservative weekly spend guide. Circle balances stay separate.</Text></View></View><PersonalBudgetPanel/><Pressable onPress={()=>router.push("/circles/personal" as any)} style={[styles.link,{borderColor:colors.border,backgroundColor:colors.card}]}><Ionicons name="receipt-outline" size={18} color={colors.indigo}/><Text style={[styles.linkText,{color:colors.onSurface}]}>Open expense & income ledger</Text><Ionicons name="chevron-forward" size={17} color={colors.muted}/></Pressable></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1},page:{width:"100%",maxWidth:900,alignSelf:"center",padding:SPACING.xl,paddingBottom:120},head:{flexDirection:"row",gap:12,alignItems:"flex-start",marginBottom:20},back:{width:42,height:42,borderRadius:14,borderWidth:1,alignItems:"center",justifyContent:"center"},eyebrow:{fontSize:9,fontWeight:"900",letterSpacing:1.1},title:{fontFamily:FONT_DISPLAY,fontSize:28,fontWeight:"900",marginTop:3},sub:{fontSize:11,lineHeight:17,marginTop:4,maxWidth:650},link:{minHeight:56,borderRadius:18,borderWidth:1,paddingHorizontal:14,flexDirection:"row",gap:9,alignItems:"center"},linkText:{flex:1,fontSize:11,fontWeight:"900"}});
