import React, { useCallback, useMemo, useState } from "react";
import { Alert, Platform, Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useRouter } from "expo-router";
import { circlesApi } from "@/src/api/circles";
import { useTheme } from "@/src/theme_context/ThemeContext";
import { FONT_DISPLAY, RADIUS, SPACING } from "@/src/theme";

const money = (paise = 0) => `₹${(Number(paise || 0) / 100).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
const csvCell = (value: unknown) => `"${String(value ?? "").replace(/"/g, '""')}"`;

export default function CircleExportScreen() {
  const router = useRouter(); const { colors } = useTheme(); const styles = useMemo(() => makeStyles(colors), [colors]);
  const [circles, setCircles] = useState<any[]>([]); const [circleId, setCircleId] = useState(""); const [detail, setDetail] = useState<any>(null);
  const loadCircle = useCallback(async (id: string) => { if (!id) return; try { setDetail(await circlesApi.get(id)); } catch (e: any) { Alert.alert("Couldn't load Circle", e?.message || "Try again"); } }, []);
  const load = useCallback(async () => { const rows = await circlesApi.list().catch(() => []); const list = Array.isArray(rows) ? rows : []; setCircles(list); const id = circleId || list[0]?.group_id || ""; setCircleId(id); if (id) await loadCircle(id); }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const select = async (id: string) => { setCircleId(id); await loadCircle(id); };

  const csv = () => {
    const header = ["type","date","description","category","amount_inr","from","to","paid_by","note"].map(csvCell).join(",");
    const expenses = (detail?.expenses || []).map((e: any) => ["expense",e.created_at,e.description,e.category,(Number(e.amount_paise||0)/100).toFixed(2),"","",e.paid_by_name||e.paid_by,e.notes||""].map(csvCell).join(","));
    const names = new Map((detail?.members || []).map((m: any) => [m.user_id, m.name]));
    const settlements = (detail?.settlements || []).map((s: any) => ["settlement",s.created_at,"Settlement","",(Number(s.amount_paise||0)/100).toFixed(2),names.get(s.from_user_id)||s.from_user_id,names.get(s.to_user_id)||s.to_user_id,"",s.note||""].map(csvCell).join(","));
    return [header, ...expenses, ...settlements].join("\n");
  };
  const exportCsv = async () => {
    const content = csv(); const name = String(detail?.group?.name || "circle").replace(/[^a-z0-9]+/gi,"-").toLowerCase();
    if (Platform.OS === "web" && typeof document !== "undefined") { const blob = new Blob([content], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `unipool-${name}.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 500); return; }
    await Share.share({ title: `${detail?.group?.name || "Circle"} CSV`, message: content });
  };
  const printPdf = async () => {
    if (Platform.OS === "web" && typeof window !== "undefined") { window.print(); return; }
    await Share.share({ title: `${detail?.group?.name || "Circle"} summary`, message: `UniPool Circle: ${detail?.group?.name}\nExpenses: ${detail?.expenses?.length || 0}\nSettlements: ${detail?.settlements?.length || 0}\nYour balance: ${money(detail?.my_balance_paise || 0)}` });
  };

  return <SafeAreaView style={styles.safe} edges={["top"]}><ScrollView contentContainerStyle={styles.page}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="chevron-back" size={20} color={colors.onSurface}/></Pressable><View style={{flex:1}}><Text style={styles.eyebrow}>CIRCLE RECORDS</Text><Text style={styles.title}>Export & settlement history</Text><Text style={styles.sub}>Download a CSV for your records or use the browser print dialog to save a clean PDF. Original expenses and settlements are never rewritten.</Text></View></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{circles.map((c)=><Pressable key={c.group_id} onPress={()=>select(c.group_id)} style={[styles.chip,circleId===c.group_id&&styles.chipActive]}><Text style={[styles.chipText,circleId===c.group_id&&{color:"#fff"}]}>{c.emoji||"💸"} {c.name}</Text></Pressable>)}</ScrollView>{detail ? <><View style={styles.actions}><Pressable onPress={exportCsv} style={styles.primary}><Ionicons name="download-outline" size={17} color="#fff"/><Text style={styles.primaryText}>Export CSV</Text></Pressable><Pressable onPress={printPdf} style={styles.secondary}><Ionicons name="document-outline" size={17} color={colors.indigo}/><Text style={styles.secondaryText}>{Platform.OS === "web" ? "Print / Save PDF" : "Share summary"}</Text></Pressable></View><View style={styles.metrics}><Metric label="Expenses" value={String(detail.expenses?.length||0)} styles={styles}/><Metric label="Settlements" value={String(detail.settlements?.length||0)} styles={styles}/><Metric label="Your balance" value={money(detail.my_balance_paise||0)} styles={styles}/></View><Text style={styles.sectionTitle}>Settlement history</Text>{detail.settlements?.length ? <View style={styles.stack}>{detail.settlements.map((s:any)=>{const names=new Map((detail.members||[]).map((m:any)=>[m.user_id,m.name]));return <View key={s.settlement_id} style={styles.row}><View style={styles.icon}><Ionicons name="checkmark-circle-outline" size={17} color={colors.success}/></View><View style={{flex:1}}><Text style={styles.rowTitle}>{names.get(s.from_user_id)||"Member"} → {names.get(s.to_user_id)||"Member"}</Text><Text style={styles.muted}>{new Date(s.created_at).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}{s.note?` · ${s.note}`:""}</Text></View><Text style={styles.amount}>{money(s.amount_paise)}</Text></View>})}</View> : <Text style={styles.muted}>No settlements recorded yet.</Text>}</> : <View style={styles.empty}><Text style={styles.rowTitle}>No Circle selected</Text></View>}</ScrollView></SafeAreaView>;
}
function Metric({label,value,styles}:any){return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>}
const makeStyles=(c:any)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.surface},page:{width:"100%",maxWidth:820,alignSelf:"center",padding:SPACING.lg,paddingBottom:120},header:{flexDirection:"row",gap:12,alignItems:"flex-start",marginBottom:16},back:{width:40,height:40,borderRadius:20,backgroundColor:c.card,borderWidth:1,borderColor:c.border,alignItems:"center",justifyContent:"center"},eyebrow:{color:c.saffron,fontSize:9,fontWeight:"900",letterSpacing:1.1},title:{color:c.onSurface,fontFamily:FONT_DISPLAY,fontSize:27,fontWeight:"900",marginTop:3},sub:{color:c.muted,fontSize:11,lineHeight:17,marginTop:4},chips:{gap:7,paddingBottom:14},chip:{minHeight:36,borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.surface2,paddingHorizontal:10,alignItems:"center",justifyContent:"center"},chipActive:{backgroundColor:c.indigo,borderColor:c.indigo},chipText:{color:c.onSurface,fontSize:9,fontWeight:"900"},actions:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:12},primary:{minHeight:42,borderRadius:21,backgroundColor:c.indigo,flexDirection:"row",alignItems:"center",gap:6,paddingHorizontal:13},primaryText:{color:"#fff",fontSize:10,fontWeight:"900"},secondary:{minHeight:42,borderRadius:21,borderWidth:1,borderColor:c.indigo,backgroundColor:c.card,flexDirection:"row",alignItems:"center",gap:6,paddingHorizontal:13},secondaryText:{color:c.indigo,fontSize:10,fontWeight:"900"},metrics:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:22},metric:{flexGrow:1,flexBasis:150,minHeight:78,borderRadius:RADIUS.lg,borderWidth:1,borderColor:c.border,backgroundColor:c.card,padding:12,justifyContent:"space-between"},metricValue:{color:c.onSurface,fontSize:18,fontWeight:"900"},metricLabel:{color:c.muted,fontSize:9,fontWeight:"800"},sectionTitle:{color:c.onSurface,fontSize:16,fontWeight:"900",marginBottom:9},stack:{gap:7},row:{minHeight:60,borderRadius:14,borderWidth:1,borderColor:c.border,backgroundColor:c.card,flexDirection:"row",alignItems:"center",gap:9,paddingHorizontal:10},icon:{width:34,height:34,borderRadius:11,backgroundColor:c.surface2,alignItems:"center",justifyContent:"center"},rowTitle:{color:c.onSurface,fontSize:10,fontWeight:"900"},muted:{color:c.muted,fontSize:9,lineHeight:14},amount:{color:c.onSurface,fontSize:10,fontWeight:"900"},empty:{minHeight:160,alignItems:"center",justifyContent:"center",backgroundColor:c.card,borderWidth:1,borderColor:c.border,borderRadius:RADIUS.lg}});