import React, { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useRouter } from "expo-router";
import { circlesApi } from "@/src/api/circles";
import { utilityApi } from "@/src/api/utility";
import { useTheme } from "@/src/theme_context/ThemeContext";
import { FONT_DISPLAY, RADIUS, SPACING } from "@/src/theme";

export default function CircleInviteScreen() {
  const router = useRouter(); const { colors } = useTheme(); const styles = useMemo(() => makeStyles(colors), [colors]);
  const [circles, setCircles] = useState<any[]>([]); const [circleId, setCircleId] = useState(""); const [email, setEmail] = useState(""); const [provider, setProvider] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false);
  const load = useCallback(async () => { setLoading(true); const [groups, health] = await Promise.allSettled([circlesApi.list(), utilityApi.health()]); if (groups.status === "fulfilled") { const rows = Array.isArray(groups.value) ? groups.value : []; setCircles(rows); setCircleId((id) => id || rows[0]?.group_id || ""); } if (health.status === "fulfilled") setProvider(health.value?.invite_email_provider || null); setLoading(false); }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const send = async () => { const address = email.trim().toLowerCase(); if (!circleId || !address.includes("@")) return Alert.alert("Check invite", "Choose a Circle and enter a valid email."); setSending(true); try { const result = await utilityApi.sendCircleInvite(circleId, address); if (result.exists) Alert.alert("Already on UniPool", "This student already has a UniPool account. Add them from Circle member search."); else if (result.sent) { setEmail(""); Alert.alert("Invite sent", `UniPool sent the Circle invite${result.provider ? ` via ${result.provider}` : ""}.`); } else Alert.alert("Direct email unavailable", "The invite was saved, but no working SendGrid/Resend sender is configured. Use the existing Circle email-composer invite as fallback."); } catch (e: any) { Alert.alert("Couldn't send invite", e?.message || "Try again"); } finally { setSending(false); } };
  return <SafeAreaView style={styles.safe} edges={["top"]}><ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="chevron-back" size={20} color={colors.onSurface} /></Pressable><View style={{ flex: 1 }}><Text style={styles.eyebrow}>CIRCLE INVITES</Text><Text style={styles.title}>Send from UniPool</Text><Text style={styles.sub}>Direct branded email when the deployment has SendGrid or Resend configured. The existing composer invite remains the fallback.</Text></View></View><View style={styles.status}><Ionicons name={provider ? "checkmark-circle-outline" : "information-circle-outline"} size={18} color={provider ? colors.success : colors.saffron} /><Text style={styles.statusText}>{provider ? `Direct sender: ${provider}` : "No direct sender detected in this environment."}</Text></View>{loading ? <View style={styles.center}><ActivityIndicator color={colors.indigo} /></View> : circles.length ? <View style={styles.card}><Text style={styles.label}>Circle</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{circles.map((circle) => <Pressable key={circle.group_id} onPress={() => setCircleId(circle.group_id)} style={[styles.chip, circleId === circle.group_id && styles.chipActive]}><Text style={[styles.chipText, circleId === circle.group_id && { color: "#fff" }]}>{circle.emoji || "💸"} {circle.name}</Text></Pressable>)}</ScrollView><Text style={styles.label}>Email</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="student@example.com" placeholderTextColor={colors.muted} style={styles.input} /><Pressable disabled={sending} onPress={send} style={styles.primary}>{sending ? <ActivityIndicator color="#fff" /> : <><Ionicons name="mail-outline" size={17} color="#fff" /><Text style={styles.primaryText}>Send invite</Text></>}</Pressable></View> : <View style={styles.empty}><Text style={styles.cardTitle}>Create or join a Circle first</Text><Pressable onPress={() => router.push("/circles" as any)}><Text style={styles.link}>Open Circles</Text></Pressable></View>}</ScrollView></SafeAreaView>;
}
const makeStyles = (c: any) => StyleSheet.create({ safe:{flex:1,backgroundColor:c.surface},page:{width:"100%",maxWidth:720,alignSelf:"center",padding:SPACING.lg,paddingBottom:120},header:{flexDirection:"row",gap:12,alignItems:"flex-start",marginBottom:16},back:{width:40,height:40,borderRadius:20,backgroundColor:c.card,borderWidth:1,borderColor:c.border,alignItems:"center",justifyContent:"center"},eyebrow:{color:c.saffron,fontSize:9,fontWeight:"900",letterSpacing:1.1},title:{color:c.onSurface,fontFamily:FONT_DISPLAY,fontSize:27,fontWeight:"900",marginTop:3},sub:{color:c.muted,fontSize:11,lineHeight:17,marginTop:4},status:{flexDirection:"row",gap:8,alignItems:"center",backgroundColor:c.surface2,borderWidth:1,borderColor:c.border,borderRadius:RADIUS.lg,padding:12,marginBottom:12},statusText:{color:c.muted,fontSize:10},center:{minHeight:160,alignItems:"center",justifyContent:"center"},card:{backgroundColor:c.card,borderWidth:1,borderColor:c.border,borderRadius:RADIUS.lg,padding:14,gap:10},label:{color:c.onSurface,fontSize:10,fontWeight:"900"},chips:{gap:7},chip:{minHeight:36,borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.surface2,paddingHorizontal:10,alignItems:"center",justifyContent:"center"},chipActive:{backgroundColor:c.indigo,borderColor:c.indigo},chipText:{color:c.onSurface,fontSize:9,fontWeight:"900"},input:{minHeight:44,borderRadius:12,borderWidth:1,borderColor:c.border,backgroundColor:c.surface2,color:c.onSurface,paddingHorizontal:11},primary:{minHeight:44,borderRadius:22,backgroundColor:c.indigo,flexDirection:"row",gap:6,alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontSize:10,fontWeight:"900"},empty:{minHeight:150,alignItems:"center",justifyContent:"center",gap:8,backgroundColor:c.card,borderWidth:1,borderColor:c.border,borderRadius:RADIUS.lg},cardTitle:{color:c.onSurface,fontSize:13,fontWeight:"900"},link:{color:c.indigo,fontSize:10,fontWeight:"900"} });