import React, { useCallback, useMemo, useRef, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useRouter } from "expo-router";
import { api } from "@/src/api/client";
import { peopleApi } from "@/src/api/v3";
import { useTheme } from "@/src/theme_context/ThemeContext";
import { FONT_DISPLAY, RADIUS, SPACING } from "@/src/theme";

type Note = { notification_id:string; source:"legacy"|"v3"; title:string; body:string; category?:string; action_url?:string; read_at?:string|null; created_at:string };
const ICONS:Record<string,keyof typeof Ionicons.glyphMap>={match:"people-outline",request:"person-add-outline",trip:"navigate-outline",trip_stage:"navigate-outline",chat:"chatbubble-outline",route_alert:"notifications-outline",circle_expense:"wallet-outline",circle_reminder:"cash-outline",rating:"star-outline",games:"game-controller-outline",general:"sparkles-outline"};
function relativeTime(value:string){const d=Math.max(0,Date.now()-new Date(value).getTime()),m=Math.floor(d/60000);if(m<1)return"now";if(m<60)return`${m}m`;const h=Math.floor(m/60);if(h<24)return`${h}h`;return`${Math.floor(h/24)}d`;}

export default function NotificationsScreen(){
 const router=useRouter();const{colors}=useTheme();const styles=useMemo(()=>makeStyles(colors),[colors]);const loaded=useRef(false);
 const[items,setItems]=useState<Note[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null);
 const load=useCallback(async(quiet=false)=>{if(!quiet&&!loaded.current)setLoading(true);else setRefreshing(true);setError(null);try{const[legacy,v3]=await Promise.allSettled([api.notifications(false,80),peopleApi.notifications(80)]);const all:Note[]=[];if(legacy.status==="fulfilled")for(const n of legacy.value.items||[])all.push({...n,source:"legacy"});if(v3.status==="fulfilled")for(const n of v3.value||[])all.push({notification_id:n.id,source:"v3",title:n.title,body:n.body,category:n.type||"general",action_url:n.route||undefined,read_at:n.read_at,created_at:n.created_at});all.sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime());setItems(all);loaded.current=true;if(legacy.status==="rejected"&&v3.status==="rejected")setError("Couldn't refresh notifications.");}finally{setLoading(false);setRefreshing(false)}},[]);
 useFocusEffect(useCallback(()=>{load(loaded.current)},[load]));const unread=items.filter(n=>!n.read_at).length;
 const open=async(note:Note)=>{if(!note.read_at){setItems(p=>p.map(n=>n.notification_id===note.notification_id&&n.source===note.source?{...n,read_at:new Date().toISOString()}:n));if(note.source==="v3")peopleApi.readNotification(note.notification_id).catch(()=>{});else api.readNotification(note.notification_id).catch(()=>{});}if(note.action_url)router.push(note.action_url as any)};
 const readAll=async()=>{setItems(p=>p.map(n=>({...n,read_at:n.read_at||new Date().toISOString()})));await Promise.allSettled([api.readAllNotifications(),peopleApi.readAllNotifications()])};
 return <SafeAreaView style={styles.safe} edges={["top","bottom"]}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="chevron-back" size={21} color={colors.onSurface}/></Pressable><View style={{flex:1}}><Text style={styles.eyebrow}>UPDATES</Text><Text style={styles.title}>Notifications</Text></View>{unread>0?<Pressable onPress={readAll} style={styles.readAll}><Text style={styles.readAllText}>Mark all read</Text></Pressable>:null}</View>{loading?<View style={styles.center}><ActivityIndicator color={colors.indigo}/></View>:<ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)} tintColor={colors.indigo}/>}>{error?<Pressable onPress={()=>load(true)} style={styles.errorCard}><Ionicons name="refresh" size={19} color={colors.indigo}/><Text style={styles.errorText}>{error} Tap to retry.</Text></Pressable>:null}<View style={styles.summary}><View><Text style={styles.summaryNum}>{unread}</Text><Text style={styles.summaryLabel}>unread</Text></View><Text style={styles.summaryCopy}>Trips, chats, Circle money, saved-route alerts and campus activity are merged here.</Text></View>{items.length===0?<View style={styles.empty}><Ionicons name="notifications-off-outline" size={32} color={colors.muted}/><Text style={styles.emptyTitle}>You're caught up</Text><Text style={styles.muted}>New UniPool activity will appear here.</Text></View>:<View style={styles.stack}>{items.map(note=>{const fresh=!note.read_at,category=note.category||"general";return <Pressable key={`${note.source}:${note.notification_id}`} onPress={()=>open(note)} style={[styles.note,fresh&&styles.noteUnread]}><View style={styles.iconWrap}><Ionicons name={ICONS[category]||ICONS.general} size={19} color={fresh?colors.indigo:colors.muted}/></View><View style={{flex:1}}><View style={styles.noteTop}><Text style={styles.noteTitle}>{note.title}</Text><Text style={styles.time}>{relativeTime(note.created_at)}</Text></View><Text style={styles.noteBody}>{note.body}</Text></View>{fresh?<View style={styles.dot}/>:null}</Pressable>})}</View>}</ScrollView>}</SafeAreaView>
}
const makeStyles=(colors:any)=>StyleSheet.create({safe:{flex:1,backgroundColor:colors.surface},header:{minHeight:68,flexDirection:"row",alignItems:"center",gap:11,paddingHorizontal:SPACING.lg,borderBottomWidth:1,borderBottomColor:colors.border,backgroundColor:colors.card},back:{width:40,height:40,borderRadius:20,backgroundColor:colors.surface2,alignItems:"center",justifyContent:"center"},eyebrow:{color:colors.saffron,fontSize:9,fontWeight:"900",letterSpacing:1.1},title:{color:colors.onSurface,fontSize:20,fontWeight:"900",fontFamily:FONT_DISPLAY,marginTop:2},readAll:{minHeight:38,justifyContent:"center",paddingHorizontal:11},readAllText:{color:colors.indigo,fontSize:11,fontWeight:"900"},center:{flex:1,alignItems:"center",justifyContent:"center"},content:{width:"100%",maxWidth:820,alignSelf:"center",padding:SPACING.lg,paddingBottom:120},summary:{flexDirection:"row",alignItems:"center",gap:16,borderRadius:RADIUS.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,padding:15,marginBottom:14},summaryNum:{color:colors.onSurface,fontSize:26,fontWeight:"900"},summaryLabel:{color:colors.muted,fontSize:9,fontWeight:"800"},summaryCopy:{flex:1,color:colors.muted,fontSize:11,lineHeight:17},errorCard:{flexDirection:"row",alignItems:"center",gap:8,borderRadius:RADIUS.md,backgroundColor:colors.surface2,padding:11,marginBottom:12},errorText:{color:colors.onSurface,fontSize:11,fontWeight:"700"},stack:{gap:8},note:{minHeight:76,flexDirection:"row",alignItems:"center",gap:11,borderRadius:RADIUS.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,padding:12},noteUnread:{backgroundColor:colors.surface2,borderColor:colors.indigo},iconWrap:{width:40,height:40,borderRadius:13,backgroundColor:colors.card,alignItems:"center",justifyContent:"center"},noteTop:{flexDirection:"row",alignItems:"center",gap:8},noteTitle:{flex:1,color:colors.onSurface,fontSize:12,fontWeight:"900"},time:{color:colors.muted,fontSize:9,fontWeight:"700"},noteBody:{color:colors.muted,fontSize:10,lineHeight:15,marginTop:3},dot:{width:7,height:7,borderRadius:4,backgroundColor:colors.indigo},empty:{minHeight:260,alignItems:"center",justifyContent:"center",gap:7},emptyTitle:{color:colors.onSurface,fontSize:15,fontWeight:"900"},muted:{color:colors.muted,fontSize:11}});
