import React, { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Linking, Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { api } from "@/src/api/client";
import { peopleApi } from "@/src/api/v3";
import { useAuth } from "@/src/auth/AuthContext";
import { useTheme } from "@/src/theme_context/ThemeContext";
import TripV3Panel from "@/src/components/TripV3Panel";
import TripFeedbackCard from "@/src/components/TripFeedbackCard";
import { SPACING, FONT_DISPLAY } from "@/src/theme";

export default function TripToolsScreen(){
 const{poolId}=useLocalSearchParams<{poolId:string}>();const router=useRouter(),{user}=useAuth(),{colors}=useTheme(),styles=useMemo(()=>makeStyles(colors),[colors]);const[pool,setPool]=useState<any>(null),[contacts,setContacts]=useState<any[]>([]),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);const[p,c]=await Promise.allSettled([api.getPool(String(poolId)),peopleApi.trustedContacts()]);if(p.status==="fulfilled")setPool(p.value);else Alert.alert("Trip unavailable",(p.reason as any)?.message||"Try again.");if(c.status==="fulfilled")setContacts(c.value||[]);setLoading(false)},[poolId]);useFocusEffect(useCallback(()=>{load()},[load]));
 if(loading&&!pool)return<SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator color={colors.indigo}/></View></SafeAreaView>;if(!pool)return null;
 const mine=pool.user_id===user?.user_id,travellers=pool.confirmed_travelers||[],participant=mine||travellers.some((t:any)=>t.user_id===user?.user_id);const summary=`UniPool trip: ${pool.from_location} → ${pool.to_location}\n${new Date(pool.travel_datetime).toLocaleString()}\n${pool.meeting_point?.label?`Meeting: ${pool.meeting_point.label}\n`:""}Open: https://uni-pool-ruddy.vercel.app/pool/${pool.pool_id}`;
 const shareContact=async(c:any)=>{if(c.email)return Linking.openURL(`mailto:${encodeURIComponent(c.email)}?subject=${encodeURIComponent("My UniPool trip")}&body=${encodeURIComponent(summary)}`);if(c.phone)return Linking.openURL(`sms:${c.phone}?body=${encodeURIComponent(summary)}`);await Share.share({message:summary})};
 return<SafeAreaView style={styles.safe} edges={["top"]}><ScrollView contentContainerStyle={styles.page}><View style={styles.head}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="chevron-back" size={20} color={colors.onSurface}/></Pressable><View style={{flex:1}}><Text style={styles.eyebrow}>TRIP MODE</Text><Text style={styles.title}>{pool.from_location} → {pool.to_location}</Text><Text style={styles.sub}>Live coordination is kept separate from the public ride listing and only available to confirmed trip members.</Text></View><Pressable onPress={()=>router.push(`/pool/${pool.pool_id}` as any)} style={styles.linkBtn}><Text style={styles.linkText}>Ride details</Text></Pressable></View>{participant?<><TripV3Panel poolId={pool.pool_id} mine={mine} participant={participant}/><View style={styles.safety}><View style={styles.safetyHead}><Ionicons name="shield-checkmark-outline" size={21} color={colors.success}/><View style={{flex:1}}><Text style={styles.safetyTitle}>Share with someone you trust</Text><Text style={styles.sub}>This sends a summary—not continuous location—unless you explicitly turn on live location above.</Text></View></View>{contacts.length?<View style={styles.contactWrap}>{contacts.map((c:any)=><Pressable key={c.id} onPress={()=>shareContact(c)} style={styles.contact}><Ionicons name={c.email?"mail-outline":"chatbubble-outline"} size={16} color={colors.indigo}/><Text style={styles.contactText}>{c.name}</Text></Pressable>)}</View>:<Pressable onPress={()=>router.push("/people" as any)} style={styles.addContact}><Ionicons name="person-add-outline" size={16} color={colors.indigo}/><Text style={styles.linkText}>Add a trusted contact</Text></Pressable>}</View><TripFeedbackCard pool={pool}/></>:<View style={styles.blocked}><Ionicons name="lock-closed-outline" size={26} color={colors.muted}/><Text style={styles.safetyTitle}>Trip tools unlock after confirmation</Text><Text style={styles.sub}>Join this ride first. Live location, polls and final fare are private to confirmed travellers.</Text></View>}</ScrollView></SafeAreaView>
}
const makeStyles=(colors:any)=>StyleSheet.create({safe:{flex:1,backgroundColor:colors.surface},page:{width:"100%",maxWidth:900,alignSelf:"center",padding:SPACING.lg,paddingBottom:120},center:{flex:1,alignItems:"center",justifyContent:"center"},head:{flexDirection:"row",gap:12,alignItems:"flex-start"},back:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface2,alignItems:"center",justifyContent:"center"},eyebrow:{color:colors.saffron,fontSize:9,fontWeight:"900",letterSpacing:1.1},title:{color:colors.onSurface,fontSize:24,fontWeight:"900",fontFamily:FONT_DISPLAY,marginTop:2},sub:{color:colors.muted,fontSize:10,lineHeight:16,marginTop:4},linkBtn:{minHeight:38,borderRadius:19,borderWidth:1,borderColor:colors.border,paddingHorizontal:12,alignItems:"center",justifyContent:"center"},linkText:{color:colors.indigo,fontSize:10,fontWeight:"900"},safety:{marginTop:14,borderRadius:20,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,padding:15},safetyHead:{flexDirection:"row",gap:9,alignItems:"flex-start"},safetyTitle:{color:colors.onSurface,fontSize:13,fontWeight:"900"},contactWrap:{flexDirection:"row",flexWrap:"wrap",gap:7,marginTop:12},contact:{minHeight:38,borderRadius:19,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface2,paddingHorizontal:11,flexDirection:"row",alignItems:"center",gap:6},contactText:{color:colors.onSurface2,fontSize:10,fontWeight:"800"},addContact:{marginTop:12,flexDirection:"row",alignItems:"center",gap:6},blocked:{marginTop:30,minHeight:260,borderRadius:22,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,alignItems:"center",justifyContent:"center",padding:30,gap:7}});
