import React, { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Platform, Pressable, ScrollView, Share, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { circlesApi } from "@/src/api/circles";
import { circlePlusApi, moneyV3Api } from "@/src/api/v3";
import { api } from "@/src/api/client";
import { useAuth } from "@/src/auth/AuthContext";
import { useTheme } from "@/src/theme_context/ThemeContext";
import { FONT_DISPLAY, SPACING } from "@/src/theme";
const money=(p=0)=>`₹${(Math.abs(Number(p||0))/100).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
export default function CircleReport(){
 const{groupId}=useLocalSearchParams<{groupId:string}>();const router=useRouter(),{user}=useAuth(),{colors}=useTheme(),styles=useMemo(()=>makeStyles(colors),[colors]);const[data,setData]=useState<any>(null),[rides,setRides]=useState<any[]>([]),[rideDetails,setRideDetails]=useState<Record<string,any>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);const[c,r]=await Promise.allSettled([circlesApi.get(String(groupId)),circlePlusApi.rides(String(groupId))]);if(c.status==="fulfilled")setData(c.value);if(r.status==="fulfilled"){setRides(r.value||[]);const pairs=await Promise.allSettled((r.value||[]).slice(0,12).map((x:any)=>api.getPool(x.pool_id)));const map:Record<string,any>={};pairs.forEach((p,i)=>{if(p.status==="fulfilled")map[(r.value||[])[i].pool_id]=p.value});setRideDetails(map)}setLoading(false)},[groupId]);useFocusEffect(useCallback(()=>{load()},[load]));
 if(loading&&!data)return<SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator color={colors.indigo}/></View></SafeAreaView>;if(!data)return null;
 const admins=new Set(data.group?.admins||[]),isAdmin=admins.has(user?.user_id),mine=(data.simplified||[]).filter((s:any)=>s.from_user_id===user?.user_id||s.to_user_id===user?.user_id);const settleOne=async(s:any)=>{setBusy(`${s.from_user_id}:${s.to_user_id}`);try{await circlesApi.settle(String(groupId),{from_user_id:s.from_user_id,to_user_id:s.to_user_id,amount_paise:s.amount_paise});await load()}catch(e:any){Alert.alert("Couldn't record settlement",e.message)}finally{setBusy(null)}};
 const settleAll=()=>Alert.alert("Record all simplified settlements?","This marks the displayed recommended payments as already paid. It does not transfer money or rewrite original expenses.",[{text:"Cancel",style:"cancel"},{text:"Record settlements",onPress:async()=>{setBusy("all");try{for(const s of data.simplified||[])await circlesApi.settle(String(groupId),{from_user_id:s.from_user_id,to_user_id:s.to_user_id,amount_paise:s.amount_paise});await load()}catch(e:any){Alert.alert("Stopped before completion",e.message)}finally{setBusy(null)}}}]);
 const rows=[...["Date","Description","Category","Paid by","Amount"].map(x=>`"${x}"`)].join(",")+"\n"+(data.expenses||[]).map((e:any)=>[new Date(e.created_at).toISOString().slice(0,10),e.description,e.category,e.paid_by_name||e.paid_by,(Number(e.amount_paise||0)/100).toFixed(2)].map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\n");
 const exportCsv=async()=>{if(Platform.OS==="web"&&typeof document!=="undefined"){const blob=new Blob([rows],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${String(data.group?.name||"circle").replace(/[^a-z0-9]+/gi,"-").toLowerCase()}-expenses.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);return}await Share.share({message:rows})};
 const print=()=>{if(Platform.OS==="web"&&typeof window!=="undefined")window.print();else Share.share({message:`${data.group?.name} Circle report\nYour balance: ${money(data.my_balance_paise)}\nExpenses: ${data.expenses?.length||0}`})};
 const importFare=async(poolId:string)=>{setBusy(`ride:${poolId}`);try{const result=await moneyV3Api.tripFareToCircle(poolId,String(groupId),{paid_by:user?.user_id,description:`Ride fare · ${rideDetails[poolId]?.from_location||"Trip"} → ${rideDetails[poolId]?.to_location||""}`});Alert.alert(result.already_exists?"Already in Circle":"Fare added to Circle",result.already_exists?"This trip fare was already imported.":`${money(result.amount_paise)} split across ${result.participants} Circle member traveller${result.participants===1?"":"s"}.`);await load()}catch(e:any){Alert.alert("Couldn't import fare",e.message)}finally{setBusy(null)}};
 return <SafeAreaView style={styles.safe} edges={["top"]}><ScrollView contentContainerStyle={styles.page}><View style={styles.head}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="chevron-back" size={20} color={colors.onSurface}/></Pressable><View style={{flex:1}}><Text style={styles.eyebrow}>CIRCLE REPORT</Text><Text style={styles.title}>{data.group?.emoji||"💸"} {data.group?.name}</Text><Text style={styles.sub}>A transparent ledger view. Simplification changes settlement paths, never the underlying expenses.</Text></View><View style={styles.actions}><Pressable onPress={exportCsv} style={styles.icon}><Ionicons name="download-outline" size={18} color={colors.indigo}/></Pressable><Pressable onPress={print} style={styles.icon}><Ionicons name="print-outline" size={18} color={colors.indigo}/></Pressable></View></View>
 <View style={styles.metrics}>{(data.balances||[]).map((b:any)=><View key={b.user_id} style={styles.metric}><Text style={styles.metricName}>{b.name}</Text><Text style={[styles.metricValue,b.amount_paise>0&&{color:colors.success},b.amount_paise<0&&{color:colors.error}]}>{b.amount_paise>0?"gets ":b.amount_paise<0?"owes ":"settled "}{money(b.amount_paise)}</Text></View>)}</View>
 <View style={styles.panel}><View style={styles.panelHead}><View><Text style={styles.sectionTitle}>Simplified settlements</Text><Text style={styles.sub}>Fewer payments with the exact same final balances.</Text></View>{isAdmin&&data.simplified?.length?<Pressable disabled={busy==="all"} onPress={settleAll} style={styles.primary}><Text style={styles.primaryText}>{busy==="all"?"Recording…":"Settle all"}</Text></Pressable>:null}</View>{data.simplified?.length?(data.simplified||[]).map((s:any)=><View key={`${s.from_user_id}:${s.to_user_id}`} style={styles.row}><View style={{flex:1}}><Text style={styles.rowTitle}>{s.from_name} → {s.to_name}</Text><Text style={styles.sub}>{money(s.amount_paise)}</Text></View>{(isAdmin||mine.includes(s))?<Pressable disabled={!!busy} onPress={()=>settleOne(s)} style={styles.secondary}><Text style={styles.secondaryText}>{busy===`${s.from_user_id}:${s.to_user_id}`?"Saving…":"Mark paid"}</Text></Pressable>:null}</View>):<Text style={styles.sub}>This Circle is fully settled.</Text>}</View>
 <View style={styles.grid}><View style={styles.panel}><Text style={styles.sectionTitle}>This month by category</Text>{Object.entries(data.month?.categories||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1])).map(([k,v])=><View key={k} style={styles.row}><Text style={[styles.rowTitle,{flex:1,textTransform:"capitalize"}]}>{k}</Text><Text style={styles.rowTitle}>{money(Number(v))}</Text></View>)}</View><View style={styles.panel}><Text style={styles.sectionTitle}>Linked rides</Text><Text style={styles.sub}>After the final cab fare is saved in Trip Tools, import it once into this Circle.</Text>{rides.length?rides.map((r:any)=>{const p=rideDetails[r.pool_id];return <View key={r.pool_id} style={styles.row}><Pressable onPress={()=>router.push(`/pool/${r.pool_id}` as any)} style={{flex:1}}><Text style={styles.rowTitle}>{p?`${p.from_location} → ${p.to_location}`:`Ride ${String(r.pool_id).slice(-6)}`}</Text><Text style={styles.sub}>{p?new Date(p.travel_datetime).toLocaleDateString("en-IN"):"Linked trip"}</Text></Pressable><Pressable disabled={!!busy} onPress={()=>importFare(r.pool_id)} style={styles.secondary}><Text style={styles.secondaryText}>{busy===`ride:${r.pool_id}`?"Adding…":"Import fare"}</Text></Pressable></View>}):<Text style={styles.sub}>Link rides from Circle Tools first.</Text>}</View></View>
 <View style={styles.panel}><Text style={styles.sectionTitle}>Expense ledger</Text>{(data.expenses||[]).map((e:any)=><View key={e.expense_id} style={styles.expense}><View style={{flex:1}}><Text style={styles.rowTitle}>{e.description}</Text><Text style={styles.sub}>{e.category} · paid by {e.paid_by_name||"Student"} · {new Date(e.created_at).toLocaleDateString("en-IN")}</Text></View><Text style={styles.amount}>{money(e.amount_paise)}</Text></View>)}</View></ScrollView></SafeAreaView>
}
const makeStyles=(c:any)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.surface},page:{width:"100%",maxWidth:1040,alignSelf:"center",padding:SPACING.xl,paddingBottom:130},center:{flex:1,alignItems:"center",justifyContent:"center"},head:{flexDirection:"row",gap:12,alignItems:"flex-start",marginBottom:18},back:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:c.border,backgroundColor:c.surface2,alignItems:"center",justifyContent:"center"},eyebrow:{color:c.saffron,fontSize:9,fontWeight:"900",letterSpacing:1.1},title:{color:c.onSurface,fontFamily:FONT_DISPLAY,fontSize:27,fontWeight:"900",marginTop:3},sub:{color:c.muted,fontSize:9,lineHeight:15,marginTop:3},actions:{flexDirection:"row",gap:7},icon:{width:40,height:40,borderRadius:20,borderWidth:1,borderColor:c.border,backgroundColor:c.card,alignItems:"center",justifyContent:"center"},metrics:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:12},metric:{flexGrow:1,flexBasis:160,minHeight:78,borderRadius:17,borderWidth:1,borderColor:c.border,backgroundColor:c.card,padding:12,justifyContent:"center"},metricName:{color:c.muted,fontSize:9,fontWeight:"800"},metricValue:{color:c.onSurface,fontSize:14,fontWeight:"900",marginTop:5},panel:{borderRadius:20,borderWidth:1,borderColor:c.border,backgroundColor:c.card,padding:15,marginBottom:12},panelHead:{flexDirection:"row",alignItems:"flex-start",justifyContent:"space-between",gap:10},sectionTitle:{color:c.onSurface,fontSize:14,fontWeight:"900"},row:{minHeight:48,borderTopWidth:1,borderTopColor:c.border,flexDirection:"row",alignItems:"center",gap:8,paddingVertical:7},rowTitle:{color:c.onSurface,fontSize:10,fontWeight:"900"},primary:{minHeight:36,borderRadius:18,backgroundColor:c.indigo,paddingHorizontal:12,alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontSize:9,fontWeight:"900"},secondary:{minHeight:34,borderRadius:17,borderWidth:1,borderColor:c.indigo,paddingHorizontal:10,alignItems:"center",justifyContent:"center"},secondaryText:{color:c.indigo,fontSize:9,fontWeight:"900"},grid:{flexDirection:"row",flexWrap:"wrap",gap:12},expense:{minHeight:56,borderTopWidth:1,borderTopColor:c.border,flexDirection:"row",alignItems:"center",gap:10},amount:{color:c.onSurface,fontSize:11,fontWeight:"900"}});
