import React, { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { circlesApi } from "@/src/api/circles";
import { circlePlusApi } from "@/src/api/v3";
import { api } from "@/src/api/client";
import { useAuth } from "@/src/auth/AuthContext";
import { useTheme } from "@/src/theme_context/ThemeContext";
import { RADIUS, SPACING, FONT_DISPLAY } from "@/src/theme";

const money=(p=0)=>`₹${(Number(p||0)/100).toLocaleString("en-IN")}`;
export default function CircleTools(){
 const{groupId}=useLocalSearchParams<{groupId:string}>();const router=useRouter(),{user}=useAuth(),{colors}=useTheme(),styles=useMemo(()=>makeStyles(colors),[colors]);
 const[data,setData]=useState<any>(null),[recurring,setRecurring]=useState<any[]>([]),[polls,setPolls]=useState<any[]>([]),[rides,setRides]=useState<any[]>([]),[myPools,setMyPools]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null);
 const[showRecurring,setShowRecurring]=useState(false),[desc,setDesc]=useState(""),[amount,setAmount]=useState(""),[frequency,setFrequency]=useState<"weekly"|"monthly">("monthly"),[payer,setPayer]=useState("");
 const[showPoll,setShowPoll]=useState(false),[question,setQuestion]=useState(""),[options,setOptions]=useState(["",""]);const[selectedExpense,setSelectedExpense]=useState<any>(null),[comments,setComments]=useState<any[]>([]),[comment,setComment]=useState("");
 const load=useCallback(async()=>{setLoading(true);const[c,r,p,l,m]=await Promise.allSettled([circlesApi.get(String(groupId)),circlePlusApi.recurring(String(groupId)),circlePlusApi.polls(String(groupId)),circlePlusApi.rides(String(groupId)),api.myPools()]);if(c.status==="fulfilled"){setData(c.value);if(!payer)setPayer(user?.user_id||c.value?.members?.[0]?.user_id||"")}if(r.status==="fulfilled")setRecurring(r.value||[]);if(p.status==="fulfilled")setPolls(p.value||[]);if(l.status==="fulfilled")setRides(l.value||[]);if(m.status==="fulfilled")setMyPools(m.value||[]);setLoading(false)},[groupId,user?.user_id,payer]);useFocusEffect(useCallback(()=>{load()},[load]));
 const members=data?.members||[];const createRecurring=async()=>{const paise=Math.round(Number(amount)*100);if(!desc.trim()||paise<=0)return Alert.alert("Check recurring expense");setBusy("recurring");try{await circlePlusApi.createRecurring(String(groupId),{description:desc.trim(),amount_paise:paise,category:"other",frequency,paid_by:payer,participant_ids:members.map((m:any)=>m.user_id),next_due_at:new Date().toISOString()});setDesc("");setAmount("");setShowRecurring(false);await load()}catch(e:any){Alert.alert("Couldn't save recurring expense",e.message)}finally{setBusy(null)}};
 const openChat=async()=>{setBusy("chat");try{const c=await circlePlusApi.ensureChat(String(groupId));router.push(`/chat/group/${c.conversation_id}` as any)}catch(e:any){Alert.alert("Couldn't open Circle chat",e.message)}finally{setBusy(null)}};
 const createPoll=async()=>{const opts=options.map(x=>x.trim()).filter(Boolean);if(question.trim().length<3||opts.length<2)return Alert.alert("Add a question and two options");setBusy("poll");try{await circlePlusApi.createPoll(String(groupId),{question:question.trim(),options:opts});setQuestion("");setOptions(["",""]);setShowPoll(false);await load()}catch(e:any){Alert.alert("Couldn't create poll",e.message)}finally{setBusy(null)}};
 const vote=async(id:string,i:number)=>{await circlePlusApi.votePoll(id,i);load()};const remind=async(m:any)=>{try{await circlePlusApi.remind(String(groupId),m.user_id);Alert.alert("Reminder sent",`${m.name} will see it in UniPool notifications.`)}catch(e:any){Alert.alert("Couldn't send reminder",e.message)}};
 const chooseExpense=async(e:any)=>{setSelectedExpense(e);try{setComments(await circlePlusApi.comments(String(groupId),e.expense_id))}catch{setComments([])}};const addComment=async()=>{if(!selectedExpense||!comment.trim())return;await circlePlusApi.addComment(String(groupId),selectedExpense.expense_id,comment.trim());setComment("");chooseExpense(selectedExpense)};
 if(loading&&!data)return<SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator color={colors.indigo}/></View></SafeAreaView>;if(!data)return null;
 return<SafeAreaView style={styles.safe} edges={["top"]}><ScrollView contentContainerStyle={styles.page}><View style={styles.head}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="chevron-back" size={20} color={colors.onSurface}/></Pressable><View style={{flex:1}}><Text style={styles.eyebrow}>CIRCLE COORDINATION</Text><Text style={styles.title}>{data.group?.emoji||"💸"} {data.group?.name}</Text><Text style={styles.sub}>Money, chat, polls and shared rides stay inside the same friend group.</Text></View><Pressable onPress={openChat} style={styles.primary}><Ionicons name="chatbubbles-outline" size={16} color="#fff"/><Text style={styles.primaryText}>{busy==="chat"?"Opening…":"Circle chat"}</Text></Pressable></View>
 <View style={styles.grid}><View style={styles.panel}><View style={styles.panelHead}><View><Text style={styles.sectionTitle}>Recurring expenses</Text><Text style={styles.sub}>Wi‑Fi, rent, maid, subscriptions or weekly groceries.</Text></View><Pressable onPress={()=>setShowRecurring(v=>!v)} style={styles.icon}><Ionicons name={showRecurring?"close":"add"} size={18} color={colors.indigo}/></Pressable></View>{showRecurring?<View style={styles.form}><TextInput value={desc} onChangeText={setDesc} placeholder="Wi‑Fi, rent…" placeholderTextColor={colors.muted} style={styles.input}/><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="₹ Amount" placeholderTextColor={colors.muted} style={styles.input}/><View style={styles.wrap}>{(["weekly","monthly"] as const).map(f=><Pressable key={f} onPress={()=>setFrequency(f)} style={[styles.chip,frequency===f&&styles.chipOn]}><Text style={[styles.chipText,frequency===f&&{color:"#fff"}]}>{f}</Text></Pressable>)}</View><Text style={styles.label}>Usually paid by</Text><View style={styles.wrap}>{members.map((m:any)=><Pressable key={m.user_id} onPress={()=>setPayer(m.user_id)} style={[styles.chip,payer===m.user_id&&styles.chipOn]}><Text style={[styles.chipText,payer===m.user_id&&{color:"#fff"}]}>{m.user_id===user?.user_id?"You":m.name.split(" ")[0]}</Text></Pressable>)}</View><Pressable onPress={createRecurring} style={styles.primary}><Text style={styles.primaryText}>Save recurring expense</Text></Pressable></View>:null}{recurring.length?recurring.map((r:any)=><View key={r.id} style={styles.row}><View style={{flex:1}}><Text style={styles.rowTitle}>{r.description}</Text><Text style={styles.sub}>{money(r.amount_paise)} · {r.frequency} · next {new Date(r.next_due_at).toLocaleDateString()}</Text></View><Pressable onPress={async()=>{await circlePlusApi.deleteRecurring(String(groupId),r.id);load()}}><Ionicons name="trash-outline" size={17} color={colors.error}/></Pressable></View>):<Text style={styles.sub}>No recurring expenses yet.</Text>}</View>
 <View style={styles.panel}><View style={styles.panelHead}><View><Text style={styles.sectionTitle}>Group polls</Text><Text style={styles.sub}>Decide things without 40 chat messages.</Text></View><Pressable onPress={()=>setShowPoll(v=>!v)} style={styles.icon}><Ionicons name={showPoll?"close":"add"} size={18} color={colors.indigo}/></Pressable></View>{showPoll?<View style={styles.form}><TextInput value={question} onChangeText={setQuestion} placeholder="Where should we eat?" placeholderTextColor={colors.muted} style={styles.input}/>{options.map((v,i)=><TextInput key={i} value={v} onChangeText={t=>setOptions(o=>o.map((x,j)=>j===i?t:x))} placeholder={`Option ${i+1}`} placeholderTextColor={colors.muted} style={styles.input}/>)}<View style={styles.wrap}><Pressable onPress={()=>setOptions(o=>o.length<6?[...o,""]:o)} style={styles.secondary}><Text style={styles.secondaryText}>+ option</Text></Pressable><Pressable onPress={createPoll} style={styles.primary}><Text style={styles.primaryText}>Create poll</Text></Pressable></View></View>:null}{polls.slice(0,6).map((p:any)=><View key={p.id} style={styles.poll}><Text style={styles.rowTitle}>{p.question}</Text>{(p.options||[]).map((o:string,i:number)=><Pressable key={i} onPress={()=>vote(p.id,i)} style={[styles.option,p.my_vote===i&&{borderColor:colors.indigo,backgroundColor:colors.surface2}]}><Text style={styles.chipText}>{o}</Text><Text style={styles.sub}>{p.counts?.[i]||0}</Text></Pressable>)}</View>)}</View></View>
 <View style={styles.grid}><View style={styles.panel}><Text style={styles.sectionTitle}>Payment nudges</Text><Text style={styles.sub}>A lightweight reminder—not an accusation or automatic debit.</Text>{members.filter((m:any)=>m.user_id!==user?.user_id).map((m:any)=><View key={m.user_id} style={styles.row}><Text style={[styles.rowTitle,{flex:1}]}>{m.name}</Text><Pressable onPress={()=>remind(m)} style={styles.secondary}><Ionicons name="notifications-outline" size={14} color={colors.indigo}/><Text style={styles.secondaryText}>Remind</Text></Pressable></View>)}</View>
 <View style={styles.panel}><Text style={styles.sectionTitle}>Linked rides</Text><Text style={styles.sub}>Attach a UniPool ride to this friend group.</Text>{myPools.filter((p:any)=>!rides.some((r:any)=>r.pool_id===p.pool_id)).slice(0,4).map((p:any)=><Pressable key={p.pool_id} onPress={async()=>{await circlePlusApi.linkRide(String(groupId),p.pool_id);load()}} style={styles.row}><View style={{flex:1}}><Text style={styles.rowTitle}>{p.from_location} → {p.to_location}</Text><Text style={styles.sub}>{new Date(p.travel_datetime).toLocaleDateString()}</Text></View><Ionicons name="add-circle-outline" size={19} color={colors.indigo}/></Pressable>)}{rides.map((r:any)=><View key={r.pool_id} style={styles.row}><Pressable style={{flex:1}} onPress={()=>router.push(`/pool/${r.pool_id}` as any)}><Text style={styles.rowTitle}>Ride {String(r.pool_id).slice(-6)}</Text><Text style={styles.sub}>Open linked journey</Text></Pressable><Pressable onPress={async()=>{await circlePlusApi.unlinkRide(String(groupId),r.pool_id);load()}}><Ionicons name="close-circle-outline" size={18} color={colors.error}/></Pressable></View>)}</View></View>
 <View style={styles.panel}><Text style={styles.sectionTitle}>Expense discussion</Text><Text style={styles.sub}>Tap an expense to keep clarifications next to the money.</Text><View style={styles.wrap}>{(data.expenses||[]).slice(0,10).map((e:any)=><Pressable key={e.expense_id} onPress={()=>chooseExpense(e)} style={[styles.chip,selectedExpense?.expense_id===e.expense_id&&styles.chipOn]}><Text style={[styles.chipText,selectedExpense?.expense_id===e.expense_id&&{color:"#fff"}]}>{e.description}</Text></Pressable>)}</View>{selectedExpense?<View style={styles.comments}>{comments.map((c:any)=><View key={c.id} style={styles.comment}><Text style={styles.rowTitle}>{c.name}</Text><Text style={styles.sub}>{c.body}</Text></View>)}<View style={styles.inline}><TextInput value={comment} onChangeText={setComment} placeholder="Clarify this expense…" placeholderTextColor={colors.muted} style={[styles.input,{flex:1}]}/><Pressable onPress={addComment} style={styles.icon}><Ionicons name="send" size={16} color={colors.indigo}/></Pressable></View></View>:null}</View>
 </ScrollView></SafeAreaView>
}
const makeStyles=(colors:any)=>StyleSheet.create({safe:{flex:1,backgroundColor:colors.surface},page:{width:"100%",maxWidth:1050,alignSelf:"center",padding:SPACING.lg,paddingBottom:130},center:{flex:1,alignItems:"center",justifyContent:"center"},head:{flexDirection:"row",gap:12,alignItems:"flex-start",marginBottom:18},back:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface2,alignItems:"center",justifyContent:"center"},eyebrow:{color:colors.saffron,fontSize:9,fontWeight:"900",letterSpacing:1.1},title:{color:colors.onSurface,fontSize:24,fontWeight:"900",fontFamily:FONT_DISPLAY,marginTop:2},sub:{color:colors.muted,fontSize:10,lineHeight:15,marginTop:3},grid:{flexDirection:"row",flexWrap:"wrap",gap:12,marginBottom:12},panel:{flexGrow:1,flexBasis:440,borderRadius:20,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,padding:15},panelHead:{flexDirection:"row",alignItems:"flex-start",justifyContent:"space-between",gap:8},sectionTitle:{color:colors.onSurface,fontSize:15,fontWeight:"900"},icon:{width:36,height:36,borderRadius:18,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface2,alignItems:"center",justifyContent:"center"},primary:{minHeight:38,borderRadius:19,backgroundColor:colors.indigo,paddingHorizontal:13,flexDirection:"row",gap:6,alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontSize:9,fontWeight:"900"},secondary:{minHeight:34,borderRadius:17,borderWidth:1,borderColor:colors.indigo,paddingHorizontal:10,flexDirection:"row",gap:5,alignItems:"center",justifyContent:"center"},secondaryText:{color:colors.indigo,fontSize:9,fontWeight:"900"},form:{marginTop:12,gap:7},input:{minHeight:40,borderRadius:12,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface2,paddingHorizontal:10,color:colors.onSurface},wrap:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:8},chip:{minHeight:32,borderRadius:16,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface2,paddingHorizontal:10,alignItems:"center",justifyContent:"center"},chipOn:{backgroundColor:colors.indigo,borderColor:colors.indigo},chipText:{color:colors.onSurface2,fontSize:9,fontWeight:"800"},label:{color:colors.onSurface2,fontSize:9,fontWeight:"900",marginTop:3},row:{minHeight:50,borderTopWidth:1,borderTopColor:colors.border,flexDirection:"row",alignItems:"center",gap:8,paddingVertical:8},rowTitle:{color:colors.onSurface,fontSize:10,fontWeight:"900"},poll:{marginTop:10,borderTopWidth:1,borderTopColor:colors.border,paddingTop:9},option:{minHeight:34,borderRadius:12,borderWidth:1,borderColor:colors.border,paddingHorizontal:9,marginTop:5,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},comments:{marginTop:10,gap:7},comment:{borderLeftWidth:2,borderLeftColor:colors.indigo,paddingLeft:9},inline:{flexDirection:"row",alignItems:"center",gap:7,marginTop:6}});
