import React, { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import * as Haptics from "expo-haptics";

import { useTheme } from "@/src/theme_context/ThemeContext";
import { FONT_DISPLAY, RADIUS, SPACING } from "@/src/theme";
import GameShareButton from "@/src/components/GameShareButton";

const STATIONS=[["NDLS","New Delhi Railway Station"],["SC","Secunderabad Junction"],["HYB","Hyderabad Deccan (Nampally)"],["KCG","Kacheguda"],["CSTM","Chhatrapati Shivaji Maharaj Terminus"],["BCT","Mumbai Central"],["HWH","Howrah Junction"],["SDAH","Sealdah"],["MAS","MGR Chennai Central"],["SBC","KSR Bengaluru City"],["PUNE","Pune Junction"],["ADI","Ahmedabad Junction"],["JP","Jaipur Junction"],["LKO","Lucknow Charbagh"],["BSB","Varanasi Junction"],["PNBE","Patna Junction"],["BBS","Bhubaneswar"],["ERS","Ernakulam Junction"],["TVC","Thiruvananthapuram Central"],["AII","Ajmer Junction"]] as const;
function shuffle<T>(items:T[]){return [...items].sort(()=>Math.random()-.5);}
export default function StationCodes(){
 const router=useRouter();const{colors}=useTheme();const styles=useMemo(()=>makeStyles(colors),[colors]);const[round]=useState(()=>shuffle(STATIONS as any).slice(0,8));const[index,setIndex]=useState(0);const[score,setScore]=useState(0);const[picked,setPicked]=useState<string|null>(null);const[done,setDone]=useState(false);const current=round[index] as readonly[string,string];const reverse=index%2===1;const answer=reverse?current[0]:current[1];const distractors=useMemo(()=>shuffle((STATIONS as readonly(readonly[string,string])[]).filter(x=>x[0]!==current?.[0])).slice(0,3).map(x=>reverse?x[0]:x[1]),[index,reverse]);const options=useMemo(()=>shuffle([answer,...distractors]),[answer,distractors]);
 const choose=(value:string)=>{if(picked)return;setPicked(value);if(value===answer){setScore(n=>n+1);Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);}else Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning);setTimeout(()=>{if(index+1>=round.length)setDone(true);else{setIndex(n=>n+1);setPicked(null);}},800);};
 return <SafeAreaView style={styles.safe} edges={["top","bottom"]}><View style={styles.header}><Pressable onPress={()=>router.back()}><Ionicons name="chevron-back" size={24} color={colors.onSurface}/></Pressable><Text style={styles.progress}>{done?"Complete":`${index+1} / ${round.length}`}</Text><Text style={styles.progress}>Score {score}</Text></View>{done?<View style={styles.center}><View style={styles.heroIcon}><Ionicons name="train" size={36} color={colors.saffron}/></View><Text style={styles.title}>Platform score: {score} / {round.length}</Text><Text style={styles.sub}>Useful code knowledge for actual Indian rail travel.</Text><GameShareButton game="Station Codes" result={`I scored ${score}/${round.length}`}/><Pressable onPress={()=>router.replace("/games/station-codes" as any)} style={styles.primary}><Text style={styles.primaryText}>Fresh round</Text></Pressable><Pressable onPress={()=>router.back()} style={styles.ghost}><Text style={styles.ghostText}>Back</Text></Pressable></View>:<View style={styles.content}><Text style={styles.eyebrow}>STATION CODES</Text><Text style={styles.prompt}>{reverse?current[1]:current[0]}</Text><Text style={styles.sub}>{reverse?"Which station code belongs here?":"Which station uses this code?"}</Text><View style={styles.options}>{options.map(option=>{const correct=picked&&option===answer;const wrong=picked===option&&option!==answer;return <Pressable key={option} onPress={()=>choose(option)} style={[styles.option,correct&&styles.correct,wrong&&styles.wrong]}><Text numberOfLines={2} style={[styles.optionText,(correct||wrong)&&{color:"#fff"}]}>{option}</Text>{correct?<Ionicons name="checkmark-circle" size={20} color="#fff"/>:null}</Pressable>;})}</View></View>}</SafeAreaView>;
}
const makeStyles=(colors:any)=>StyleSheet.create({safe:{flex:1,backgroundColor:colors.surface},header:{minHeight:60,paddingHorizontal:SPACING.lg,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},progress:{color:colors.muted,fontSize:11,fontWeight:"800"},content:{flex:1,width:"100%",maxWidth:700,alignSelf:"center",justifyContent:"center",padding:SPACING.xl},eyebrow:{color:colors.saffron,fontSize:10,fontWeight:"900",letterSpacing:1.2},prompt:{color:colors.onSurface,fontFamily:FONT_DISPLAY,fontSize:34,lineHeight:42,fontWeight:"900",marginTop:8},sub:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:6,textAlign:"center"},options:{gap:9,marginTop:24},option:{minHeight:60,borderRadius:RADIUS.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,paddingHorizontal:16,paddingVertical:11,flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},optionText:{flex:1,color:colors.onSurface,fontSize:13,fontWeight:"800"},correct:{backgroundColor:colors.success,borderColor:colors.success},wrong:{backgroundColor:colors.error,borderColor:colors.error},center:{flex:1,width:"100%",maxWidth:520,alignSelf:"center",alignItems:"center",justifyContent:"center",padding:SPACING.xl,gap:8},heroIcon:{width:76,height:76,borderRadius:24,backgroundColor:colors.card,borderWidth:1,borderColor:colors.border,alignItems:"center",justifyContent:"center"},title:{color:colors.onSurface,fontFamily:FONT_DISPLAY,fontSize:25,fontWeight:"900",marginTop:8,textAlign:"center"},primary:{width:"100%",minHeight:48,borderRadius:24,backgroundColor:colors.indigo,alignItems:"center",justifyContent:"center",marginTop:12},primaryText:{color:"#fff",fontWeight:"900"},ghost:{width:"100%",minHeight:46,borderRadius:23,borderWidth:1,borderColor:colors.border,alignItems:"center",justifyContent:"center",marginTop:2},ghostText:{color:colors.indigo,fontWeight:"900"}});