import React, { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { api } from "@/src/api/client";
import { moneyV3Api } from "@/src/api/v3";
import { useAuth } from "@/src/auth/AuthContext";
import { useTheme } from "@/src/theme_context/ThemeContext";
import { FONT_DISPLAY, SPACING } from "@/src/theme";
const TIMES=[15,30,60,120,180],DETOURS=[0,1,3,5,10],CABS=["any","sedan","xl / suv","two cabs okay"];
export default function MatchPreferences(){
 const{poolId}=useLocalSearchParams<{poolId:string}>();const router=useRouter(),{user}=useAuth(),{colors}=useTheme(),styles=useMemo(()=>makeStyles(colors),[colors]);const[pool,setPool]=useState<any>(null),[prefs,setPrefs]=useState<any>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);const[p,x]=await Promise.allSettled([api.getPool(String(poolId)),moneyV3Api.tripPreferences(String(poolId))]);if(p.status==="fulfilled")setPool(p.value);if(x.status==="fulfilled")setPrefs(x.value);setLoading(false)},[poolId]);useFocusEffect(useCallback(()=>{load()},[load]));
 if(loading&&!prefs)return<SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator color={colors.indigo}/></View></SafeAreaView>;if(!prefs)return null;const mine=pool?.user_id===user?.user_id;
 const save=async()=>{setSaving(true);try{setPrefs(await moneyV3Api.saveTripPreferences(String(poolId),prefs));Alert.alert("Match preferences saved","These preferences stay attached to this journey and can be used to explain compatibility without changing the public route/time.")}catch(e:any){Alert.alert("Couldn't save preferences",e.message)}finally{setSaving(false)}};
 return <SafeAreaView style={styles.safe} edges={["top"]}><ScrollView contentContainerStyle={styles.page}><View style={styles.head}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="chevron-back" size={20} color={colors.onSurface}/></Pressable><View style={{flex:1}}><Text style={styles.eyebrow}>MATCH CONTROLS</Text><Text style={styles.title}>How flexible is this trip?</Text><Text style={styles.sub}>{pool?`${pool.from_location} → ${pool.to_location}`:"Your journey"}. These preferences are private matching context, not promises shown as fake scores.</Text></View></View>{!mine?<View style={styles.notice}><Ionicons name="lock-closed-outline" size={18} color={colors.muted}/><Text style={styles.sub}>Only the trip owner can change matching preferences.</Text></View>:<><Section title="Time flexibility" sub="How far from your posted departure can a genuinely useful match be?" styles={styles}><View style={styles.wrap}>{TIMES.map(n=><Chip key={n} active={prefs.time_flex_minutes===n} label={n<60?`±${n} min`:`±${n/60} hr${n>60?"s":""}`} onPress={()=>setPrefs({...prefs,time_flex_minutes:n})} styles={styles}/>)}</View></Section><Section title="Maximum detour" sub="How much pickup/drop deviation are you willing to consider?" styles={styles}><View style={styles.wrap}>{DETOURS.map(n=><Chip key={n} active={Number(prefs.max_detour_km)===n} label={n===0?"No detour":`${n} km`} onPress={()=>setPrefs({...prefs,max_detour_km:n})} styles={styles}/>)}</View></Section><Section title="Cab preference" sub="Used as compatibility context, never as a hard booking guarantee." styles={styles}><View style={styles.wrap}>{CABS.map(v=><Chip key={v} active={prefs.cab_preference===v} label={v} onPress={()=>setPrefs({...prefs,cab_preference:v})} styles={styles}/>)}</View></Section><View style={styles.grid}><Toggle label="Prefer a quiet ride" sub="Useful when you want minimal conversation/work time." value={!!prefs.quiet_ride} onPress={()=>setPrefs({...prefs,quiet_ride:!prefs.quiet_ride})} colors={colors} styles={styles}/><Toggle label="Luggage flexible" sub="You can adapt if another traveller has extra luggage." value={prefs.luggage_flexible!==false} onPress={()=>setPrefs({...prefs,luggage_flexible:!prefs.luggage_flexible})} colors={colors} styles={styles}/></View><Pressable disabled={saving} onPress={save} style={styles.primary}>{saving?<ActivityIndicator color="#fff"/>:<><Ionicons name="checkmark" size={17} color="#fff"/><Text style={styles.primaryText}>Save match preferences</Text></>}</Pressable></>}</ScrollView></SafeAreaView>
}
function Section({title,sub,styles,children}:any){return<View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><Text style={styles.sub}>{sub}</Text>{children}</View>}function Chip({active,label,onPress,styles}:any){return<Pressable onPress={onPress} style={[styles.chip,active&&styles.chipOn]}><Text style={[styles.chipText,active&&{color:"#fff"}]}>{label}</Text></Pressable>}function Toggle({label,sub,value,onPress,colors,styles}:any){return<Pressable onPress={onPress} style={styles.toggle}><View style={{flex:1}}><Text style={styles.sectionTitle}>{label}</Text><Text style={styles.sub}>{sub}</Text></View><Ionicons name={value?"checkmark-circle":"ellipse-outline"} size={23} color={value?colors.success:colors.muted}/></Pressable>}
const makeStyles=(c:any)=>StyleSheet.create({safe:{flex:1,backgroundColor:c.surface},page:{width:"100%",maxWidth:800,alignSelf:"center",padding:SPACING.xl,paddingBottom:120},center:{flex:1,alignItems:"center",justifyContent:"center"},head:{flexDirection:"row",gap:12,alignItems:"flex-start",marginBottom:18},back:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:c.border,backgroundColor:c.surface2,alignItems:"center",justifyContent:"center"},eyebrow:{color:c.saffron,fontSize:9,fontWeight:"900",letterSpacing:1.1},title:{color:c.onSurface,fontFamily:FONT_DISPLAY,fontSize:27,fontWeight:"900",marginTop:3},sub:{color:c.muted,fontSize:10,lineHeight:16,marginTop:3},notice:{minHeight:80,borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.card,padding:14,flexDirection:"row",alignItems:"center",gap:9},section:{borderRadius:19,borderWidth:1,borderColor:c.border,backgroundColor:c.card,padding:15,marginBottom:10},sectionTitle:{color:c.onSurface,fontSize:12,fontWeight:"900"},wrap:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:10},chip:{minHeight:34,borderRadius:17,borderWidth:1,borderColor:c.border,backgroundColor:c.surface2,paddingHorizontal:11,alignItems:"center",justifyContent:"center"},chipOn:{backgroundColor:c.indigo,borderColor:c.indigo},chipText:{color:c.onSurface2,fontSize:9,fontWeight:"900",textTransform:"capitalize"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},toggle:{flexGrow:1,flexBasis:300,minHeight:82,borderRadius:18,borderWidth:1,borderColor:c.border,backgroundColor:c.card,padding:14,flexDirection:"row",alignItems:"center",gap:10},primary:{marginTop:14,minHeight:46,borderRadius:23,backgroundColor:c.indigo,flexDirection:"row",gap:7,alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontSize:10,fontWeight:"900"}});
