import React, { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { moneyV3Api } from "@/src/api/v3";
import { useTheme } from "@/src/theme_context/ThemeContext";

const CATEGORIES=["food","groceries","travel","academics","rent","utilities","entertainment","shopping","other"];
const money=(p=0)=>`₹${(Math.abs(Number(p||0))/100).toLocaleString("en-IN",{maximumFractionDigits:0})}`;
export default function PersonalBudgetPanel(){
 const{colors}=useTheme(),styles=useMemo(()=>makeStyles(colors),[colors]);const[data,setData]=useState<any>(null),[category,setCategory]=useState("food"),[limit,setLimit]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{setData(await moneyV3Api.budgets())}catch{}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const save=async()=>{const n=Number(limit);if(!Number.isFinite(n)||n<0)return Alert.alert("Check budget","Enter a valid monthly limit.");setBusy(true);try{await moneyV3Api.setBudget(category,Math.round(n*100),data?.month);setLimit("");await load()}catch(e:any){Alert.alert("Couldn't save budget",e.message)}finally{setBusy(false)}};
 return <View style={styles.card}><View style={styles.head}><View><Text style={styles.eyebrow}>MONTHLY BUDGETS</Text><Text style={styles.title}>Spend with context</Text><Text style={styles.sub}>Personal spending only. Circle debts remain separate.</Text></View><Ionicons name="pie-chart-outline" size={22} color={colors.saffron}/></View>{loading&&!data?<ActivityIndicator color={colors.indigo} style={{marginTop:20}}/>:<><View style={styles.metrics}><View><Text style={styles.big}>{money(data?.remaining_budget_paise||0)}</Text><Text style={styles.meta}>remaining across set budgets</Text></View><View><Text style={styles.big}>{money(data?.safe_to_spend_week_paise||0)}</Text><Text style={styles.meta}>safe to spend this week</Text></View></View><View style={styles.wrap}>{CATEGORIES.map(c=><Pressable key={c} onPress={()=>setCategory(c)} style={[styles.chip,category===c&&styles.chipOn]}><Text style={[styles.chipText,category===c&&{color:"#fff"}]}>{c}</Text></Pressable>)}</View><View style={styles.inline}><TextInput value={limit} onChangeText={setLimit} keyboardType="decimal-pad" placeholder={`Monthly ${category} limit ₹`} placeholderTextColor={colors.muted} style={styles.input}/><Pressable disabled={busy} onPress={save} style={styles.save}>{busy?<ActivityIndicator size="small" color="#fff"/>:<Text style={styles.saveText}>Set</Text>}</Pressable></View>{data?.budgets?.length?<View style={styles.list}>{data.budgets.map((b:any)=>{const ratio=b.limit_paise?Math.min(1,Number(b.spent_paise||0)/Number(b.limit_paise)):0;return <View key={b.category} style={styles.row}><View style={{flex:1}}><View style={styles.rowTop}><Text style={styles.rowTitle}>{b.category}</Text><Text style={styles.meta}>{money(b.spent_paise)} / {money(b.limit_paise)}</Text></View><View style={styles.track}><View style={[styles.fill,{width:`${ratio*100}%`,backgroundColor:b.over_paise>0?colors.error:colors.indigo}]}/></View></View><Pressable onPress={async()=>{await moneyV3Api.deleteBudget(b.category,data.month);load()}}><Ionicons name="trash-outline" size={16} color={colors.muted}/></Pressable></View>})}</View>:<Text style={[styles.sub,{marginTop:12}]}>Set one or two category limits to make this useful; you do not need to budget every rupee.</Text>}</>}</View>
}
const makeStyles=(c:any)=>StyleSheet.create({card:{borderRadius:20,borderWidth:1,borderColor:c.border,backgroundColor:c.card,padding:15,marginBottom:18},head:{flexDirection:"row",justifyContent:"space-between",gap:10},eyebrow:{color:c.saffron,fontSize:9,fontWeight:"900",letterSpacing:1},title:{color:c.onSurface,fontSize:15,fontWeight:"900",marginTop:3},sub:{color:c.muted,fontSize:9,lineHeight:14,marginTop:3},metrics:{flexDirection:"row",flexWrap:"wrap",gap:28,marginTop:14},big:{color:c.onSurface,fontSize:20,fontWeight:"900"},meta:{color:c.muted,fontSize:9},wrap:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:14},chip:{minHeight:30,borderRadius:15,borderWidth:1,borderColor:c.border,backgroundColor:c.surface2,paddingHorizontal:9,alignItems:"center",justifyContent:"center"},chipOn:{backgroundColor:c.indigo,borderColor:c.indigo},chipText:{color:c.onSurface2,fontSize:8,fontWeight:"900",textTransform:"capitalize"},inline:{flexDirection:"row",gap:7,marginTop:10},input:{flex:1,minHeight:40,borderRadius:12,borderWidth:1,borderColor:c.border,backgroundColor:c.surface2,paddingHorizontal:10,color:c.onSurface},save:{minWidth:64,borderRadius:20,backgroundColor:c.indigo,alignItems:"center",justifyContent:"center"},saveText:{color:"#fff",fontSize:9,fontWeight:"900"},list:{marginTop:12,gap:7},row:{minHeight:48,borderTopWidth:1,borderTopColor:c.border,flexDirection:"row",alignItems:"center",gap:9,paddingTop:7},rowTop:{flexDirection:"row",justifyContent:"space-between",gap:8},rowTitle:{color:c.onSurface,fontSize:9,fontWeight:"900",textTransform:"capitalize"},track:{height:5,borderRadius:3,backgroundColor:c.surface2,overflow:"hidden",marginTop:6},fill:{height:"100%"}});
