import React, { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { tripV3Api } from "@/src/api/v3";
import { useTheme } from "@/src/theme_context/ThemeContext";
import { RADIUS, SPACING } from "@/src/theme";

const STAGES = [
  ["matching", "Matching"], ["confirmed", "Confirmed"], ["meeting", "Meeting"], ["travelling", "Travelling"], ["completed", "Completed"],
] as const;

export default function TripV3Panel({ poolId, mine, participant }: { poolId: string; mine: boolean; participant: boolean }) {
  const { colors } = useTheme(); const styles = useMemo(() => makeStyles(colors), [colors]);
  const [state, setState] = useState<any>(null); const [live, setLive] = useState<any[]>([]); const [polls, setPolls] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string | null>(null);
  const [pollOpen, setPollOpen] = useState(false); const [question, setQuestion] = useState(""); const [options, setOptions] = useState(["", ""]); const [fare, setFare] = useState("");
  const load = useCallback(async () => { if (!participant) return; setLoading(true); const [s,l,p]=await Promise.allSettled([tripV3Api.state(poolId),tripV3Api.live(poolId),tripV3Api.polls(poolId)]); if(s.status==="fulfilled")setState(s.value); if(l.status==="fulfilled")setLive(l.value||[]); if(p.status==="fulfilled")setPolls(p.value||[]); setLoading(false); }, [poolId, participant]);
  useEffect(()=>{load(); if(!participant)return; const t=setInterval(load,15000); return()=>clearInterval(t);},[load,participant]);
  if (!participant) return null;
  if (loading && !state) return <View style={styles.panel}><ActivityIndicator color={colors.indigo}/></View>;

  const setStage = async (stage:string) => { if(!mine)return; setBusy(stage); try{const next=await tripV3Api.setStage(poolId,stage);setState((s:any)=>({...s,...next}));}catch(e:any){Alert.alert("Couldn't update trip stage",e.message)}finally{setBusy(null)} };
  const setStatus = async (status:string) => { setBusy(status); try{await tripV3Api.updateLive(poolId,{status});await load();}catch(e:any){Alert.alert("Couldn't update your status",e.message)}finally{setBusy(null)} };
  const shareLocation = async () => {
    if (Platform.OS !== "web" || typeof navigator === "undefined" || !navigator.geolocation) return Alert.alert("Location unavailable", "Live location sharing is currently available in the UniPool web app when browser location permission is enabled.");
    setBusy("location"); navigator.geolocation.getCurrentPosition(async pos=>{try{await tripV3Api.updateLive(poolId,{status:"on_the_way",latitude:pos.coords.latitude,longitude:pos.coords.longitude,share_minutes:30});await load();Alert.alert("Location shared for 30 minutes","Only confirmed trip members can see it, and it expires automatically.");}catch(e:any){Alert.alert("Couldn't share location",e.message)}finally{setBusy(null)}},err=>{setBusy(null);Alert.alert("Location permission needed",err.message||"Allow location access and try again.")},{enableHighAccuracy:false,timeout:10000,maximumAge:30000});
  };
  const saveFare=async()=>{const paise=Math.round(Number(fare)*100);if(!paise)return Alert.alert("Enter the final fare");setBusy("fare");try{const next=await tripV3Api.setFare(poolId,paise);setState((s:any)=>({...s,...next}));setFare("");}catch(e:any){Alert.alert("Couldn't save final fare",e.message)}finally{setBusy(null)}};
  const createPoll=async()=>{const opts=options.map(v=>v.trim()).filter(Boolean);if(question.trim().length<3||opts.length<2)return Alert.alert("Add a question and at least two options");setBusy("poll");try{await tripV3Api.createPoll(poolId,{question:question.trim(),options:opts});setQuestion("");setOptions(["",""]);setPollOpen(false);await load();}catch(e:any){Alert.alert("Couldn't create poll",e.message)}finally{setBusy(null)}};
  const vote=async(id:string,index:number)=>{try{await tripV3Api.votePoll(id,index);await load()}catch(e:any){Alert.alert("Couldn't vote",e.message)}};
  const currentMine=live.find(x=>x.user_id && x.status && x.name);

  return <View style={styles.panel}>
    <View style={styles.top}><View><Text style={styles.eyebrow}>LIVE COORDINATION</Text><Text style={styles.title}>Trip lifecycle & meetup</Text></View><Ionicons name="navigate-circle-outline" size={24} color={colors.indigo}/></View>
    <View style={styles.stageRow}>{STAGES.map(([value,label])=><Pressable key={value} disabled={!mine||!!busy} onPress={()=>setStage(value)} style={[styles.stage,state?.stage===value&&styles.stageActive]}><Text style={[styles.stageText,state?.stage===value&&{color:"#fff"}]}>{label}</Text></Pressable>)}</View>
    {!mine?<Text style={styles.hint}>The trip owner controls the shared lifecycle stage.</Text>:null}
    <View style={styles.grid}>
      <View style={styles.card}><Text style={styles.cardTitle}>Your live status</Text><View style={styles.wrap}>{[["getting_ready","Getting ready"],["on_the_way","On my way"],["at_pickup","At pickup"],["running_late","Running late"]].map(([v,l])=><Pressable key={v} onPress={()=>setStatus(v)} style={styles.chip}><Text style={styles.chipText}>{l}</Text></Pressable>)}</View><Pressable onPress={shareLocation} disabled={busy==="location"} style={styles.secondary}><Ionicons name="location-outline" size={16} color={colors.indigo}/><Text style={styles.secondaryText}>{busy==="location"?"Getting location…":"Share live location · 30 min"}</Text></Pressable><Text style={styles.hint}>Location is optional, trip-member-only and automatically expires.</Text></View>
      <View style={styles.card}><Text style={styles.cardTitle}>Final fare</Text>{state?.final_fare_paise?<><Text style={styles.money}>₹{(Number(state.final_fare_paise)/100).toLocaleString("en-IN")}</Text><Text style={styles.hint}>≈ ₹{(Number(state.estimated_share_paise||0)/100).toLocaleString("en-IN")} each across {state.member_count||1} travellers</Text></>:<Text style={styles.hint}>Use this after the ride. The earlier fare card remains an estimate.</Text>}{mine?<View style={styles.inline}><TextInput value={fare} onChangeText={setFare} keyboardType="decimal-pad" placeholder="Final ₹" placeholderTextColor={colors.muted} style={styles.input}/><Pressable onPress={saveFare} style={styles.small}><Text style={styles.smallText}>Save</Text></Pressable></View>:null}</View>
    </View>
    {live.length?<View style={styles.liveList}>{live.map((x:any)=><View key={x.user_id} style={styles.liveRow}><View style={[styles.dot,{backgroundColor:x.status==="running_late"?colors.saffron:colors.success}]}/><Text style={styles.liveName}>{x.name}</Text><Text style={styles.hint}>{String(x.status||"").replace(/_/g," ")}{x.location_active?" · location shared":""}</Text></View>)}</View>:null}
    <View style={styles.pollHead}><Text style={styles.cardTitle}>Ride polls</Text><Pressable onPress={()=>setPollOpen(v=>!v)}><Text style={styles.link}>{pollOpen?"Close":"New poll"}</Text></Pressable></View>
    {pollOpen?<View style={styles.pollForm}><TextInput value={question} onChangeText={setQuestion} placeholder="Leave at 6:00 or 6:30?" placeholderTextColor={colors.muted} style={styles.input}/>{options.map((v,i)=><TextInput key={i} value={v} onChangeText={t=>setOptions(o=>o.map((x,j)=>j===i?t:x))} placeholder={`Option ${i+1}`} placeholderTextColor={colors.muted} style={styles.input}/>)}<View style={styles.inline}><Pressable onPress={()=>setOptions(o=>o.length<5?[...o,""]:o)} style={styles.secondary}><Text style={styles.secondaryText}>+ option</Text></Pressable><Pressable onPress={createPoll} style={styles.small}><Text style={styles.smallText}>Create poll</Text></Pressable></View></View>:null}
    {polls.slice(0,4).map((p:any)=><View key={p.id} style={styles.poll}><Text style={styles.pollQ}>{p.question}</Text>{(p.options||[]).map((opt:string,i:number)=><Pressable key={i} onPress={()=>vote(p.id,i)} style={[styles.option,p.my_vote===i&&{borderColor:colors.indigo,backgroundColor:colors.surface2}]}><Text style={styles.optionText}>{opt}</Text><Text style={styles.hint}>{p.counts?.[i]||0}</Text></Pressable>)}</View>)}
  </View>;
}

const makeStyles=(colors:any)=>StyleSheet.create({panel:{marginTop:12,marginBottom:20,borderRadius:22,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,padding:16},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},eyebrow:{color:colors.saffron,fontSize:9,fontWeight:"900",letterSpacing:1.1},title:{color:colors.onSurface,fontSize:17,fontWeight:"900",marginTop:2},stageRow:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:14},stage:{minHeight:34,paddingHorizontal:11,borderRadius:17,borderWidth:1,borderColor:colors.border,alignItems:"center",justifyContent:"center",backgroundColor:colors.surface2},stageActive:{backgroundColor:colors.indigo,borderColor:colors.indigo},stageText:{color:colors.onSurface2,fontSize:9,fontWeight:"800"},hint:{color:colors.muted,fontSize:9,lineHeight:14,marginTop:5},grid:{flexDirection:"row",flexWrap:"wrap",gap:10,marginTop:14},card:{flexGrow:1,flexBasis:300,borderRadius:17,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface2,padding:12},cardTitle:{color:colors.onSurface,fontSize:11,fontWeight:"900"},wrap:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:9},chip:{paddingHorizontal:9,minHeight:30,borderRadius:15,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,alignItems:"center",justifyContent:"center"},chipText:{color:colors.onSurface2,fontSize:9,fontWeight:"800"},secondary:{minHeight:36,paddingHorizontal:10,borderRadius:18,borderWidth:1,borderColor:colors.indigo,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:5,marginTop:9},secondaryText:{color:colors.indigo,fontSize:9,fontWeight:"900"},money:{color:colors.onSurface,fontSize:22,fontWeight:"900",marginTop:7},inline:{flexDirection:"row",gap:7,alignItems:"center",marginTop:9},input:{flex:1,minHeight:38,borderRadius:12,borderWidth:1,borderColor:colors.border,backgroundColor:colors.card,paddingHorizontal:10,color:colors.onSurface},small:{minHeight:38,paddingHorizontal:14,borderRadius:19,backgroundColor:colors.indigo,alignItems:"center",justifyContent:"center"},smallText:{color:"#fff",fontSize:9,fontWeight:"900"},liveList:{marginTop:12,gap:5},liveRow:{minHeight:30,flexDirection:"row",alignItems:"center",gap:7},dot:{width:7,height:7,borderRadius:4},liveName:{color:colors.onSurface,fontSize:10,fontWeight:"900"},pollHead:{marginTop:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},link:{color:colors.indigo,fontSize:10,fontWeight:"900"},pollForm:{marginTop:8,gap:7},poll:{marginTop:9,borderRadius:15,borderWidth:1,borderColor:colors.border,padding:10},pollQ:{color:colors.onSurface,fontSize:11,fontWeight:"900",marginBottom:7},option:{minHeight:34,borderRadius:12,borderWidth:1,borderColor:colors.border,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:9,marginTop:5},optionText:{color:colors.onSurface2,fontSize:9,fontWeight:"800"}});
