import React, { useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { feedbackApi } from "@/src/api/v3";
import { useAuth } from "@/src/auth/AuthContext";
import { useTheme } from "@/src/theme_context/ThemeContext";

export default function TripFeedbackCard({ pool }: { pool: any }) {
 const { user }=useAuth(),{colors}=useTheme(),styles=useMemo(()=>makeStyles(colors),[colors]);
 const owner={user_id:pool.user_id||pool.owner_user_id,name:pool.user_name||"Trip owner"}; const people=[owner,...(pool.confirmed_travelers||[])].filter((p:any)=>p.user_id&&p.user_id!==user?.user_id); const[target,setTarget]=useState(people[0]?.user_id||""); const[punctuality,setPunctuality]=useState(5),[coordination,setCoordination]=useState(5),[behaviour,setBehaviour]=useState(5),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[done,setDone]=useState<string[]>([]);
 const past=new Date(pool.travel_datetime||0).getTime()<=Date.now(); if(!past||!people.length)return null;
 const submit=async()=>{if(!target)return;setBusy(true);try{await feedbackApi.submit({pool_id:pool.pool_id,rated_user_id:target,punctuality,coordination,behaviour,note:note.trim()||undefined});setDone(x=>[...new Set([...x,target])]);setNote("");Alert.alert("Feedback saved","Punctuality, coordination and behaviour are kept separate so trust stays explainable.")}catch(e:any){Alert.alert("Couldn't save feedback",e.message)}finally{setBusy(false)}};
 return <View style={styles.card}><View style={styles.head}><View style={styles.icon}><Ionicons name="star-outline" size={20} color={colors.saffron}/></View><View style={{flex:1}}><Text style={styles.title}>Post-trip feedback</Text><Text style={styles.sub}>Rate only people you actually travelled with. This feeds their transparent travel-trust summary.</Text></View></View><Text style={styles.label}>Traveller</Text><View style={styles.wrap}>{people.map((p:any)=><Pressable key={p.user_id} onPress={()=>setTarget(p.user_id)} style={[styles.chip,target===p.user_id&&styles.chipOn]}><Text style={[styles.chipText,target===p.user_id&&{color:"#fff"}]}>{p.name||"Student"}{done.includes(p.user_id)?" ✓":""}</Text></Pressable>)}</View><Rating label="Punctuality" value={punctuality} set={setPunctuality} styles={styles}/><Rating label="Coordination" value={coordination} set={setCoordination} styles={styles}/><Rating label="Behaviour" value={behaviour} set={setBehaviour} styles={styles}/><TextInput value={note} onChangeText={setNote} placeholder="Optional private-context note" placeholderTextColor={colors.muted} style={styles.input}/><Pressable disabled={busy||!target} onPress={submit} style={[styles.primary,busy&&{opacity:.6}]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={styles.primaryText}>Save feedback</Text>}</Pressable></View>
}
function Rating({label,value,set,styles}:any){return <View style={styles.rating}><Text style={styles.label}>{label}</Text><View style={styles.scoreRow}>{[1,2,3,4,5].map(n=><Pressable key={n} onPress={()=>set(n)} style={[styles.score,value===n&&styles.scoreOn]}><Text style={[styles.scoreText,value===n&&{color:"#fff"}]}>{n}</Text></Pressable>)}</View></View>}
const makeStyles=(c:any)=>StyleSheet.create({card:{marginTop:14,borderRadius:20,borderWidth:1,borderColor:c.border,backgroundColor:c.card,padding:15},head:{flexDirection:"row",gap:10,alignItems:"flex-start"},icon:{width:40,height:40,borderRadius:13,backgroundColor:c.surface2,alignItems:"center",justifyContent:"center"},title:{color:c.onSurface,fontSize:13,fontWeight:"900"},sub:{color:c.muted,fontSize:9,lineHeight:14,marginTop:3},label:{color:c.onSurface2,fontSize:9,fontWeight:"900",marginTop:11},wrap:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:7},chip:{minHeight:32,paddingHorizontal:10,borderRadius:16,borderWidth:1,borderColor:c.border,backgroundColor:c.surface2,alignItems:"center",justifyContent:"center"},chipOn:{backgroundColor:c.indigo,borderColor:c.indigo},chipText:{color:c.onSurface2,fontSize:9,fontWeight:"800"},rating:{marginTop:4},scoreRow:{flexDirection:"row",gap:6,marginTop:6},score:{width:34,height:34,borderRadius:17,borderWidth:1,borderColor:c.border,backgroundColor:c.surface2,alignItems:"center",justifyContent:"center"},scoreOn:{backgroundColor:c.indigo,borderColor:c.indigo},scoreText:{color:c.onSurface,fontSize:10,fontWeight:"900"},input:{minHeight:42,borderRadius:12,borderWidth:1,borderColor:c.border,backgroundColor:c.surface2,paddingHorizontal:10,color:c.onSurface,marginTop:12},primary:{minHeight:40,borderRadius:20,backgroundColor:c.indigo,alignItems:"center",justifyContent:"center",marginTop:9},primaryText:{color:"#fff",fontSize:10,fontWeight:"900"}});
