import React, { useEffect, useState } from "react";
import { Platform, Pressable, StyleSheet, Text, useWindowDimensions, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { usePathname, useRouter } from "expo-router";
import * as Haptics from "expo-haptics";
import { api } from "@/src/api/client";
import { peopleApi } from "@/src/api/v3";
import { useTheme } from "@/src/theme_context/ThemeContext";
import GlobalSearchPalette from "@/src/components/GlobalSearchPalette";

const NAV=[
 {label:"Home",icon:"home-outline" as const,path:"/(tabs)",match:"/"},
 {label:"Matches",icon:"people-outline" as const,path:"/(tabs)/matches",match:"/matches"},
 {label:"Circles",icon:"wallet-outline" as const,path:"/circles",match:"/circles"},
 {label:"Chats",icon:"chatbubble-outline" as const,path:"/(tabs)/messages",match:"/messages"},
 {label:"Profile",icon:"person-outline" as const,path:"/(tabs)/profile",match:"/profile"},
];
export default function WebTopBar(){
 const router=useRouter(),pathname=usePathname();const{width}=useWindowDimensions();const{colors,isDark,toggleTheme}=useTheme();const[searchOpen,setSearchOpen]=useState(false),[unread,setUnread]=useState(0);
 useEffect(()=>{if(Platform.OS!=="web"||typeof window==="undefined")return;const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setSearchOpen(true)}if(e.key==="Escape")setSearchOpen(false)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
 useEffect(()=>{if(Platform.OS!=="web")return;let alive=true;const refresh=async()=>{try{if(typeof document!=="undefined"&&document.visibilityState==="hidden")return;const[l,v]=await Promise.allSettled([api.notifications(true,1),peopleApi.notifications(50)]);let n=0;if(l.status==="fulfilled")n+=Number(l.value?.unread||0);if(v.status==="fulfilled")n+=(v.value||[]).filter((x:any)=>!x.read_at).length;if(alive)setUnread(n)}catch{}};refresh();const timer=setInterval(refresh,30000);const visible=()=>refresh();if(typeof document!=="undefined")document.addEventListener("visibilitychange",visible);return()=>{alive=false;clearInterval(timer);if(typeof document!=="undefined")document.removeEventListener("visibilitychange",visible)}},[pathname]);
 if(Platform.OS!=="web")return null;const desktop=width>=900,showActionText=width>=1260,showBrandText=width>=520;const tap=(fn:()=>void)=>{Haptics.selectionAsync();fn()};const isActive=(m:string)=>m==="/"?pathname==="/":pathname===m||pathname.startsWith(`${m}/`);
 return <><View style={[styles.bar,{backgroundColor:colors.card,borderBottomColor:colors.border}]}><Pressable onPress={()=>router.replace("/(tabs)" as any)} style={styles.brand}><View style={[styles.logo,{backgroundColor:colors.surface2,borderColor:colors.border}]}><Ionicons name="car-sport" size={19} color={colors.saffron}/></View>{showBrandText?<Text style={[styles.brandText,{color:colors.onSurface}]}>UniPool</Text>:null}</Pressable>{desktop?<View style={[styles.nav,{backgroundColor:colors.surface2,borderColor:colors.border}]}>{NAV.map(item=>{const active=isActive(item.match);return <Pressable key={item.label} onPress={()=>tap(()=>router.replace(item.path as any))} style={[styles.navItem,active&&{backgroundColor:colors.card,borderColor:colors.border}]}><Ionicons name={item.icon} size={18} color={active?(item.label==="Circles"?colors.saffron:colors.indigo):colors.muted}/><Text style={[styles.navText,{color:active?colors.onSurface:colors.muted}]}>{item.label}</Text></Pressable>})}</View>:<View style={{flex:1}}/>}<View style={styles.actions}><Pressable onPress={()=>tap(()=>setSearchOpen(true))} style={[styles.searchAction,{backgroundColor:colors.surface2,borderColor:colors.border}]}><Ionicons name="search" size={19} color={colors.indigo}/>{showActionText?<Text style={[styles.actionText,{color:colors.onSurface}]}>Search</Text>:null}</Pressable><Pressable onPress={()=>tap(()=>router.push("/post-request" as any))} style={[styles.primaryAction,{backgroundColor:colors.indigo,borderColor:colors.indigo}]}><Ionicons name="add" size={20} color="#fff"/>{showActionText?<Text style={styles.primaryActionText}>Post trip</Text>:null}</Pressable><Icon label="Notifications" icon={unread?"notifications":"notifications-outline"} color={unread?colors.saffron:colors.indigo} onPress={()=>router.push("/notifications" as any)} colors={colors} badge={unread}/><Icon label="Explore" icon="compass-outline" color={pathname==="/plan"?colors.saffron:colors.indigo} onPress={()=>router.push("/(tabs)/plan" as any)} colors={colors}/><Icon label="Games" icon="game-controller-outline" color={pathname==="/games"?colors.saffron:colors.indigo} onPress={()=>router.push("/(tabs)/games" as any)} colors={colors}/><Icon label="People" icon="person-add-outline" color={pathname==="/people"?colors.saffron:colors.indigo} onPress={()=>router.push("/people" as any)} colors={colors}/><Icon label="Settings" icon="settings-outline" color={colors.indigo} onPress={()=>router.push("/settings" as any)} colors={colors}/><Icon label="Theme" icon={isDark?"sunny-outline":"moon-outline"} color={colors.indigo} onPress={toggleTheme} colors={colors}/></View></View><GlobalSearchPalette visible={searchOpen} onClose={()=>setSearchOpen(false)}/></>
}
function Icon({label,icon,color,onPress,colors,badge=0}:{label:string;icon:any;color:string;onPress:()=>void;colors:any;badge?:number}){return <Pressable onPress={()=>{Haptics.selectionAsync();onPress()}} style={[styles.iconAction,{backgroundColor:colors.surface2,borderColor:colors.border}]} accessibilityLabel={label}><Ionicons name={icon} size={20} color={color}/>{badge?<View style={[styles.badge,{backgroundColor:colors.error}]}><Text style={styles.badgeText}>{badge>9?"9+":badge}</Text></View>:null}</Pressable>}
const styles=StyleSheet.create({bar:{height:68,width:"100%",flexDirection:"row",alignItems:"center",gap:18,paddingHorizontal:26,borderBottomWidth:StyleSheet.hairlineWidth,zIndex:50},brand:{flexDirection:"row",alignItems:"center",gap:10,minWidth:48},logo:{width:40,height:40,borderRadius:13,borderWidth:1,alignItems:"center",justifyContent:"center"},brandText:{fontSize:18,fontWeight:"900",letterSpacing:-.25},nav:{flexDirection:"row",alignItems:"center",gap:4,padding:4,borderRadius:25,borderWidth:1,marginHorizontal:"auto"},navItem:{height:42,paddingHorizontal:16,borderRadius:21,borderWidth:1,borderColor:"transparent",flexDirection:"row",alignItems:"center",gap:7},navText:{fontSize:13,fontWeight:"800"},actions:{flexDirection:"row",alignItems:"center",gap:7},searchAction:{height:42,minWidth:42,paddingHorizontal:14,borderRadius:21,borderWidth:1,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7},primaryAction:{height:42,minWidth:42,paddingHorizontal:14,borderRadius:21,borderWidth:1,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7},actionText:{fontSize:12,fontWeight:"800"},primaryActionText:{color:"#fff",fontSize:12,fontWeight:"900"},iconAction:{width:42,height:42,borderRadius:21,borderWidth:1,alignItems:"center",justifyContent:"center",position:"relative"},badge:{position:"absolute",minWidth:16,height:16,borderRadius:8,paddingHorizontal:3,right:-3,top:-3,alignItems:"center",justifyContent:"center"},badgeText:{color:"#fff",fontSize:8,fontWeight:"900"}});
