import React, { useCallback, useRef, useState, useMemo } from "react";
import { View, Text, StyleSheet, FlatList, ActivityIndicator, RefreshControl, Pressable, Platform } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useFocusEffect, useRouter } from "expo-router";

import { SPACING, RADIUS, FONT, FONT_DISPLAY } from "@/src/theme";
import { useTheme } from "@/src/theme_context/ThemeContext";
import { api } from "@/src/api/client";
import { sharedApi } from "@/src/api/shared";
import { utilityApi } from "@/src/api/utility";

type Convo = { kind: "direct" | "group"; other_user_id?: string; conversation_id?: string; name: string; picture?: string | null; last_message: string; last_at: string; unread: number; online?: boolean; members_count?: number };
function fmt(dt: string) { const d = new Date(dt); const now = new Date(); const sameDay = d.toDateString() === now.toDateString(); return sameDay ? d.toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit", timeZone: "Asia/Kolkata" }) : d.toLocaleDateString(undefined, { day: "numeric", month: "short", timeZone: "Asia/Kolkata" }); }
function convoKey(item: Convo) { return item.kind === "group" ? `group-${item.conversation_id}` : `direct-${item.other_user_id}`; }

export default function MessagesScreen() {
  const router = useRouter(); const { colors, isDark } = useTheme(); const styles = useMemo(() => makeStyles(colors, isDark), [colors, isDark]);
  const [items, setItems] = useState<Convo[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null); const [restrictedCount, setRestrictedCount] = useState(0);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const load = useCallback(async (silent = false) => {
    const [sharedResult, legacyResult, relationsResult] = await Promise.allSettled([sharedApi.listConversations(), api.listConversations(), utilityApi.relations()]);
    const restricted = new Set<string>();
    if (relationsResult.status === "fulfilled") for (const relation of relationsResult.value || []) if (relation.relation === "restricted" && relation.user_id) restricted.add(relation.user_id);
    const merged = new Map<string, Convo>();
    if (legacyResult.status === "fulfilled") for (const item of legacyResult.value || []) merged.set(convoKey(item), item);
    if (sharedResult.status === "fulfilled") for (const item of sharedResult.value || []) if (item.kind === "direct") merged.set(convoKey(item), item);
    const all = [...merged.values()].sort((a, b) => new Date(b.last_at || 0).getTime() - new Date(a.last_at || 0).getTime());
    const next = all.filter((item) => item.kind === "group" || !item.other_user_id || !restricted.has(item.other_user_id));
    setRestrictedCount(all.length - next.length);
    if (sharedResult.status === "rejected" && legacyResult.status === "rejected") {
      if (!silent) setError((sharedResult.reason as any)?.message || (legacyResult.reason as any)?.message || "Unable to load your conversations.");
    } else { setItems(next); if (!silent) setError(null); }
    if (!silent) { setLoading(false); setRefreshing(false); }
  }, []);
  useFocusEffect(useCallback(() => {
    load(); pollRef.current = setInterval(() => { if (Platform.OS !== "web" || typeof document === "undefined" || document.visibilityState !== "hidden") load(true); }, 7000);
    return () => { if (pollRef.current) clearInterval(pollRef.current); };
  }, [load]));
  const openConversation = (item: Convo) => { if (item.kind === "group" && item.conversation_id) router.push({ pathname: "/chat/group/[conversationId]", params: { conversationId: item.conversation_id } }); else if (item.other_user_id) router.push({ pathname: "/chat/[userId]", params: { userId: item.other_user_id, name: item.name } }); };

  return <SafeAreaView style={styles.safe} edges={["top"]}>
    <LinearGradient colors={isDark ? [colors.surface2, colors.surface3] : [colors.indigo, "#3949AB"]} style={styles.header}><View style={{ flexDirection: "row", alignItems: "center", gap: SPACING.md }}><View style={styles.headerIcon}><Ionicons name="chatbubbles" size={21} color={isDark ? colors.saffron : "#fff"} /></View><View><Text style={styles.title}>Chats</Text><Text style={styles.sub}>Direct and shared-trip conversations</Text></View></View>{!loading && !error && items.length > 0 ? <View style={styles.headerCount}><Text style={styles.headerCountText}>{items.length}</Text></View> : null}</LinearGradient>
    {restrictedCount > 0 ? <Pressable onPress={() => router.push("/settings" as any)} style={styles.restrictedNote}><Ionicons name="eye-off-outline" size={16} color={colors.indigo} /><Text style={styles.restrictedText}>{restrictedCount} restricted conversation{restrictedCount === 1 ? "" : "s"} hidden</Text><Text style={styles.manageText}>Manage</Text></Pressable> : null}
    {loading ? <View style={styles.center}><ActivityIndicator color={colors.indigo} /></View> : error ? <View style={styles.state}><View style={styles.stateIcon}><Ionicons name="cloud-offline-outline" size={28} color={colors.error} /></View><Text style={styles.emptyTitle}>Couldn't load chats</Text><Text style={styles.emptySub}>{error}</Text><Pressable onPress={() => { setLoading(true); load(); }} style={styles.retry}><Ionicons name="refresh" size={16} color="#fff" /><Text style={styles.retryText}>Try again</Text></Pressable></View> : <FlatList data={items} keyExtractor={convoKey} contentContainerStyle={{ padding: SPACING.lg, paddingBottom: 140 }} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }} tintColor={colors.indigo} />} ListEmptyComponent={<View style={styles.empty}><View style={styles.emptyIcon}><Ionicons name="chatbubble-ellipses-outline" size={30} color={colors.indigo} /></View><Text style={styles.emptyTitle}>No conversations yet</Text><Text style={styles.emptySub}>When you message someone or a trip group is created, it will stay here.</Text><Pressable onPress={() => router.push("/matches")} style={styles.emptyCta}><Ionicons name="sparkles" size={16} color="#fff" /><Text style={styles.emptyCtaText}>Find a match</Text></Pressable></View>} renderItem={({ item }) => <Pressable onPress={() => openConversation(item)} style={styles.row}><View style={{ position: "relative" }}><View style={[styles.avatar, item.kind === "group" && styles.groupAvatar]}><Ionicons name={item.kind === "group" ? "people" : "person"} size={19} color={item.kind === "group" ? colors.saffron : colors.indigo} /></View>{item.online && <View style={styles.onlineDot} />}</View><View style={{ flex: 1 }}><View style={styles.rowTop}><View style={styles.nameWrap}><Text style={styles.name} numberOfLines={1}>{item.name}</Text>{item.kind === "group" && <Text style={styles.groupMeta}>{item.members_count || 0} travellers</Text>}</View><Text style={styles.time}>{fmt(item.last_at)}</Text></View><View style={styles.rowBottom}><Text style={styles.preview} numberOfLines={1}>{item.last_message}</Text>{item.unread > 0 && <View style={styles.badge}><Text style={styles.badgeText}>{item.unread > 99 ? "99+" : item.unread}</Text></View>}</View></View></Pressable>} />}
  </SafeAreaView>;
}

const makeStyles = (colors: any, isDark: boolean) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.surface }, header: { paddingHorizontal: SPACING.lg, paddingTop: SPACING.md, paddingBottom: SPACING.lg, borderBottomLeftRadius: 22, borderBottomRightRadius: 22, borderBottomWidth: 1, borderBottomColor: isDark ? colors.border : "rgba(255,255,255,0.18)" }, headerIcon: { width: 40, height: 40, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: isDark ? colors.surface3 : "rgba(255,255,255,0.14)" }, headerCount: { position: "absolute", right: SPACING.lg, top: SPACING.lg, minWidth: 30, height: 30, paddingHorizontal: 8, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: isDark ? colors.surface3 : "rgba(255,255,255,0.16)" }, headerCountText: { color: isDark ? colors.onSurface : "#fff", fontWeight: "800", fontSize: 12 }, title: { color: isDark ? colors.onSurface : "#fff", fontSize: FONT["2xl"], fontWeight: "800", fontFamily: FONT_DISPLAY }, sub: { color: isDark ? colors.onSurface2 : "rgba(255,255,255,0.9)", marginTop: 2 },
  restrictedNote: { minHeight: 42, marginHorizontal: SPACING.lg, marginTop: 10, paddingHorizontal: 12, borderRadius: RADIUS.lg, backgroundColor: colors.surface2, borderWidth: 1, borderColor: colors.border, flexDirection: "row", alignItems: "center", gap: 7 }, restrictedText: { flex: 1, color: colors.onSurface2, fontSize: 10, fontWeight: "700" }, manageText: { color: colors.indigo, fontSize: 10, fontWeight: "900" },
  center: { flex: 1, alignItems: "center", justifyContent: "center" }, state: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: SPACING.xl }, stateIcon: { width: 58, height: 58, borderRadius: 29, alignItems: "center", justifyContent: "center", backgroundColor: colors.surface2, marginBottom: SPACING.md }, retry: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: SPACING.lg, backgroundColor: colors.indigo, borderRadius: RADIUS.pill, paddingHorizontal: 18, paddingVertical: 11 }, retryText: { color: "#fff", fontWeight: "800" }, empty: { alignItems: "center", paddingVertical: 80, paddingHorizontal: SPACING.xl }, emptyIcon: { width: 58, height: 58, borderRadius: 29, alignItems: "center", justifyContent: "center", backgroundColor: colors.surface2, marginBottom: SPACING.md }, emptyCta: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: SPACING.lg, backgroundColor: colors.indigo, borderRadius: RADIUS.pill, paddingHorizontal: 18, paddingVertical: 11 }, emptyCtaText: { color: "#fff", fontWeight: "800" }, emptyTitle: { marginTop: SPACING.md, fontSize: FONT.xl, fontWeight: "700", color: colors.onSurface }, emptySub: { marginTop: 4, color: colors.muted, textAlign: "center", lineHeight: 20 }, row: { flexDirection: "row", alignItems: "center", gap: SPACING.md, backgroundColor: colors.card, borderRadius: RADIUS.lg, padding: SPACING.md, marginBottom: SPACING.sm, borderWidth: 1, borderColor: colors.border }, avatar: { width: 46, height: 46, borderRadius: 23, backgroundColor: colors.cream, alignItems: "center", justifyContent: "center" }, groupAvatar: { backgroundColor: colors.surface2 }, onlineDot: { position: "absolute", bottom: 0, right: 0, width: 12, height: 12, borderRadius: 6, backgroundColor: colors.success, borderWidth: 2, borderColor: colors.card }, nameWrap: { flex: 1, minWidth: 0 }, rowTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: SPACING.sm }, name: { fontWeight: "800", color: colors.onSurface, fontSize: FONT.base }, groupMeta: { color: colors.saffron, fontSize: 10, fontWeight: "700", marginTop: 1 }, time: { color: colors.muted, fontSize: FONT.sm }, rowBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 3 }, preview: { color: colors.muted, flex: 1, marginRight: SPACING.sm }, badge: { backgroundColor: colors.saffron, borderRadius: RADIUS.pill, minWidth: 20, height: 20, alignItems: "center", justifyContent: "center", paddingHorizontal: 6 }, badgeText: { color: "#fff", fontSize: 11, fontWeight: "800" },
});
