import React, { useMemo, useState } from "react";
import { View, Text, StyleSheet, ScrollView, Pressable, Alert } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import * as Haptics from "expo-haptics";
import { SPACING, RADIUS, FONT, FONT_DISPLAY } from "@/src/theme";
import { useTheme } from "@/src/theme_context/ThemeContext";
import { useAuth } from "@/src/auth/AuthContext";

const QUICK = [
  { icon: "airplane-outline", title: "Airport rides", subtitle: "Find people heading to the airport", route: "/" },
  { icon: "train-outline", title: "Railway rides", subtitle: "Share the last mile to your station", route: "/" },
  { icon: "calendar-outline", title: "Plan ahead", subtitle: "Post a ride for today, tomorrow or later", route: "/post-request" },
];

export default function PlanScreen() {
  const router = useRouter(); const { user } = useAuth(); const { colors, isDark } = useTheme();
  const styles = useMemo(() => makeStyles(colors, isDark), [colors, isDark]); const [busy, setBusy] = useState(false);
  const openQuick = (item: any) => { Haptics.selectionAsync(); router.push(item.route as any); };
  const shareReferral = async () => { try { setBusy(true); const text = "Join me on UniPool — share rides with verified university students."; if (typeof navigator !== "undefined" && navigator.share) await navigator.share({ title: "UniPool", text }); else Alert.alert("Invite friends", text); } catch {} finally { setBusy(false); } };
  return <SafeAreaView style={styles.safe} edges={["top"]}><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.hero}><View style={styles.heroIcon}><Ionicons name="sparkles" size={22} color={colors.saffron} /></View><Text style={styles.kicker}>MAKE EVERY RIDE EASIER</Text><Text style={styles.title}>Plan your next ride</Text><Text style={styles.subtitle}>Discovery, trust and planning — together, without making UniPool complicated.</Text></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>Quick start</Text>{QUICK.map((item) => <Pressable key={item.title} onPress={() => openQuick(item)} style={styles.card}><View style={styles.cardIcon}><Ionicons name={item.icon as any} size={21} color={colors.indigo} /></View><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardSub}>{item.subtitle}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted} /></Pressable>)}</View>
    <View style={styles.section}><Text style={styles.sectionTitle}>Build trust faster</Text><View style={styles.trustCard}><TrustRow done={!!user?.college_verified} icon="shield-checkmark-outline" title="Verify your university" subtitle="Get the verified student badge" colors={colors} onPress={() => router.push("/profile" as any)} /><TrustRow done={!!user?.name} icon="person-outline" title="Complete your profile" subtitle="A fuller profile gets more requests accepted" colors={colors} onPress={() => router.push("/profile" as any)} /><TrustRow done={false} icon="star-outline" title="Rate your completed rides" subtitle="Help the next student choose confidently" colors={colors} onPress={() => router.push("/matches" as any)} /></View></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>Discover demand</Text><Pressable style={styles.feature} onPress={() => router.push("/heatmap" as any)}><View style={styles.featureIcon}><Ionicons name="flame-outline" size={24} color={colors.saffron} /></View><View style={{ flex: 1 }}><Text style={styles.featureTitle}>See where people are travelling</Text><Text style={styles.featureSub}>Spot popular airport and railway corridors before you post.</Text></View><Ionicons name="arrow-forward" size={18} color={colors.saffron} /></Pressable></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>Bring your friends</Text><View style={styles.referral}><View style={styles.referralIcon}><Ionicons name="people-outline" size={24} color={colors.indigo} /></View><View style={{ flex: 1 }}><Text style={styles.cardTitle}>More students = better matches</Text><Text style={styles.cardSub}>Invite classmates and make usual routes easier to fill.</Text></View><Pressable disabled={busy} onPress={shareReferral} style={styles.invite}><Text style={styles.inviteText}>{busy ? "…" : "Invite"}</Text></Pressable></View></View>
    <View style={styles.tip}><Ionicons name="bulb-outline" size={18} color={colors.saffron} /><Text style={styles.tipText}>Tip: add luggage and a clear pickup note when you post. Small details reduce back-and-forth in chat.</Text></View>
  </ScrollView></SafeAreaView>;
}
function TrustRow({ done, icon, title, subtitle, colors, onPress }: any) { return <Pressable onPress={onPress} style={{ flexDirection: "row", alignItems: "center", paddingVertical: 13, gap: 12 }}><View style={{ width: 38, height: 38, borderRadius: 19, backgroundColor: done ? colors.successSoft : colors.surface2, alignItems: "center", justifyContent: "center" }}><Ionicons name={done ? "checkmark" : icon} size={18} color={done ? colors.success : colors.indigo} /></View><View style={{ flex: 1 }}><Text style={{ color: colors.onSurface, fontWeight: "800", fontSize: 14 }}>{title}</Text><Text style={{ color: colors.muted, marginTop: 2, fontSize: 12 }}>{subtitle}</Text></View><Ionicons name="chevron-forward" size={16} color={colors.muted} /></Pressable>; }
const makeStyles = (colors: any, isDark: boolean) => StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.surface }, content: { padding: SPACING.lg, paddingBottom: 120 }, hero: { backgroundColor: isDark ? colors.surface2 : colors.indigo, borderRadius: RADIUS.xl, padding: 22, borderWidth: 1, borderColor: colors.border }, heroIcon: { width: 44, height: 44, borderRadius: 22, backgroundColor: isDark ? colors.card : "rgba(255,255,255,.12)", alignItems: "center", justifyContent: "center", marginBottom: 14 }, kicker: { color: isDark ? colors.saffron : "rgba(255,255,255,.72)", fontSize: 10, fontWeight: "900", letterSpacing: 1.2 }, title: { color: isDark ? colors.onSurface : "#fff", fontSize: 28, fontWeight: "900", fontFamily: FONT_DISPLAY, marginTop: 5 }, subtitle: { color: isDark ? colors.onSurface2 : "rgba(255,255,255,.78)", fontSize: 14, lineHeight: 21, marginTop: 7 }, section: { marginTop: 24 }, sectionTitle: { color: colors.onSurface, fontSize: 17, fontWeight: "900", marginBottom: 10 }, card: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: RADIUS.lg, padding: 14, marginBottom: 9 }, cardIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.surface2, alignItems: "center", justifyContent: "center" }, cardTitle: { color: colors.onSurface, fontSize: 14, fontWeight: "800" }, cardSub: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 2 }, trustCard: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: RADIUS.lg, paddingHorizontal: 14 }, feature: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: colors.card, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: colors.border, padding: 15 }, featureIcon: { width: 46, height: 46, borderRadius: 15, backgroundColor: colors.surface2, alignItems: "center", justifyContent: "center" }, featureTitle: { color: colors.onSurface, fontWeight: "800", fontSize: 14 }, featureSub: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 3 }, referral: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: colors.card, borderRadius: RADIUS.lg, borderWidth: 1, borderColor: colors.border, padding: 14 }, referralIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: colors.surface2, alignItems: "center", justifyContent: "center" }, invite: { backgroundColor: colors.saffron, borderRadius: RADIUS.pill, paddingHorizontal: 14, paddingVertical: 9 }, inviteText: { color: "#fff", fontWeight: "900", fontSize: 12 }, tip: { flexDirection: "row", gap: 9, backgroundColor: colors.surface2, borderRadius: RADIUS.md, padding: 13, marginTop: 20, borderWidth: 1, borderColor: colors.border }, tipText: { color: colors.muted, flex: 1, fontSize: 12, lineHeight: 18 } });
